### ISSUE TITLE
Turn on google maps on ios

### ISSUE THREAD

**Issue by KonstantinGreat** [venits/react-native-map-clustering#104]
on ios shows only ios maps with no clusters, provider={PROVIDER_GOOGLE} shows error or app doesnt start
question - how to start google map on ios

**Comment by jazzymb7** [comment]
@bigo104 , @KonstantinGreat Any alternatives to use google maps in iOS?

**Comment by venits** [comment]
Here is step-by-step guid on how to use GoogleMaps on iOS:
https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0
