### ISSUE TITLE
AnimateToRegion

### ISSUE THREAD

**Issue by Anytram** [venits/react-native-map-clustering#105]
Hello,
how to use animateToRegion or fitToCoordinates properties with this library?  When I'm trying in usuall way I'm getting:

> Property 'animateToRegion' does not exist on type 'ClusteredMapView'.

**Comment by venits** [comment]
Hi, I updated README.me with answers.

You can do it like this:
1. Create reference
```js
<MapView ref={ref => mapView = ref } />
```
2. Create **animate()** method
```js
const animate = () => {
  let r = {
    latitude: 42.5,
    longitude: 15.2,
    latitudeDelta: 7.5,
    longitudeDelta: 7.5,
  };
  mapView.root.animateToRegion(r, 2000);
};
```
3. You can call it onPress() for example:
```js
  <Button title="Animate" onPress={animate} />
```

**Comment by venits** [comment]
H all, I changed implementation a little bit.
Now you have to use **mapRef** instead of **ref**.

Example:
```js
<MapView mapRef={ref => this.mapView = ref} />
```
In case of any problems please open issue.
