### ISSUE TITLE
Could not find a declaration file for module 'react-native-map-clustering'

### ISSUE THREAD

**Issue by deepak-netsoft** [venits/react-native-map-clustering#109]
I am getting declaration error while installing this library @venits 

Library version : "react-native-map-clustering": "^2.0.2"

React native Version: 
"react": "16.8.3",
  "react-native": "0.59.9"

**Comment by venits** [comment]
Can you show me code where you import my module? or error log that is displaying on your device.

**Comment by gcoro** [comment]
@deepak-netsoft You can fix this by adding the following line at the end of your project index.d.ts (or whatever you have named your types declaration file. if you don't have any, then create it)

```
 declare module 'react-native-map-clustering';
```
