### ISSUE TITLE
onClusterPress not call because componentWillReceiveProps not fired in MapWithClustering .js

### ISSUE THREAD

**Issue by shenlongdemon** [venits/react-native-map-clustering#11]
HI, the first, i want to say deeply thank for you module
It's really helpful 

But i got some problems,

My code is:

 <MapView
                onClusterPress={(coordinate) => {
                    alert("11212123" + prop);
                    }} ...

In class MapWithClustering , method componentWillReceiveProps is not fired 

so method onClusterPress in class CustomMarker is undefined  --> not fired too.

Problem 2, please add more information on onClusterPress such as onClusterPress(coordinate, markers) which markers are children of clustering

Thank for your helpful module 

![componentwillreceiveprops is not fired](https://user-images.githubusercontent.com/6994283/31401264-997dbaa2-ae1c-11e7-84a2-055047916342.jpg)

**Comment by venits** [comment]
Hmm very strange componentWillReceiveProps being called in key in this module. I am not sure yet what is the problem but please follow steps below and tell me your results:

1. In componentWillReceiveProps add this to make sure it is not called.
```javascript
 console.warn('markers will receive props');
```
2. Make sure you are using MapView from my module not MapView from 'react-native-maps'.
3. Tell me your modules version of: 'react', 'react-native' and 'react-native-maps', so I can recreate the problem.
4. If nothing works please send me full source code of class with MapView in it (maybe I will find error). My email: tomasz.przybyl.it@gmail.com

**Comment by shenlongdemon** [comment]
sorry my late,
In package.json

  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-map-clustering": "^1.1.5",
    "react-native-maps": "^0.16.4"
  },

In main.js

import MapView1 from 'react-native-map-clustering';
import Marker from 'react-native-maps';

and render function 

render() {
        return (
            <View style={{ flex: 1 }}>
                <MapView1
               
                onClusterPress={(prop) => {
                    alert("11212123" + prop);
                    }}
                customClusterMarkerDesign={
                    <View style={{width:50, height:50, backgroundColor:"#00ff00"}}></View>
                }
                    style={styles.map}
                    region={{latitude: 15.654775665159686, longitude: 108.193359375,
                        latitudeDelta: 8.5, longitudeDelta: 8.5}}
                        
                   
                        
                >
                    <Marker  coordinate={{latitude: 15.654775665159686, longitude: 108.193359375}}                     
                    />
                    <Marker  coordinate={{latitude: 15.654775665159686, longitude: 108.293359375}} />
                    <Marker  coordinate={{latitude: 15.554775665159686, longitude: 108.393359375}} />
                    <Marker  coordinate={{latitude: 15.454775665159686, longitude: 108.493359375}} />
                    <Marker  coordinate={{latitude: 15.354775665159686, longitude: 108.593359375}} />
                    <Marker  coordinate={{latitude: 15.254775665159686, longitude:108.693359375}} />
                    <Marker  coordinate={{latitude: 15.154775665159686, longitude: 108.793359375}} />
                </MapView1>               
            </View>
        );
    }

Please re-check it
Thank for your support

ps: please consider if it's possible, please add more information such as
 -  onClusterPress function : add amount of markers that are merged
 -  customClusterMarkerDesign function : generally, we based on data of markers that are merged to calculate custom view for clustering. For example, when some markers are merged, i would like to get count of marker and can custom clustering marker with that number. so please add more information such as 
     customClusterMarkerDesign={(markers)
                    <View style={{width:50, height:50, backgroundColor:"#00ff00"}}>
                    <Text>markers.length</Text>
                    </View>
                }

Thanks

**Comment by venits** [comment]
It is really strange because I updated all my modules to match yours and copied whole render method and it just works fine for me. I used 'MapView1' and  'MapView' and in both cases it worked.  The problem must be somewhere else. The best way will be if you send me all files with source code so I can fully recreate your problem.

**Comment by shenlongdemon** [comment]
Because of security problem so i just send you temporary project. Sorry about that
Please recheck it and you can find out issue
Thank you so much 

[ShareLocSL.zip](https://github.com/venits/react-native-map-clustering/files/1379645/ShareLocSL.zip)

**Comment by venits** [comment]
It was my fault I am so sorry. There was 1 line of code missing in my module but I added it and now everything is working. Please install new version 1.1.6.

Those changes you suggested, I will implement them all. I am planing to do big changes in this module and make one big update in like 1-2 weeks. So be ready for that :)

**Comment by shenlongdemon** [comment]
That's cool !!!
Thank you so much
