### ISSUE TITLE
No Maintainence ? and ClusterStyle & ClusterTextStyle props are dynamic now

### ISSUE THREAD

**Issue by WrathChaos** [venits/react-native-map-clustering#112]
I guess this library is not actively maintained.  @venits I'm a volunteer to make the library active again. 

If you guys also need a dynamic clusterStyle & clusterTextStyle. Here you go: 

`"react-native-map-clustering": "git+https://github.com/WrathChaos/react-native-map-clustering.git"`

**Comment by venits** [comment]
Hi @WrathChaos 

I started refreshing this library yesterday. I will release it in few days. 
I will look at your implementation :)

Once I will release new version we can work on it together ;)

**Comment by WrathChaos** [comment]
Hello @venits 
I'm very glad to hear that :) I'm looking for the new release with excitement :O
