### ISSUE TITLE
Does this MapView receive the same props as the original?

### ISSUE THREAD

**Issue by sebackend** [venits/react-native-map-clustering#113]
I'm working on a project made with the community react-native-maps, but now i need to implement clustering for markers, this project seems to be perfect for my requirements.

My actual code is something like this

```
<MapView
          ref={map => {
            this.map = map;
          }}
          provider={PROVIDER_GOOGLE}
          style={styles.map}
          customMapStyle={mapStyle}
          showsUserLocation
          showsCompass
          showsMyLocationButton={false}
          onRegionChangeComplete={region => this.debounceChangeRegion(region)}
          onPress={() => this.toggleProjectDetails()}
          initialRegion={{
            latitude: region.latitude,
            longitude: region.longitude),
            latitudeDelta: region.latitudeDelta,
            longitudeDelta: region.longitudeDelta
          }}
        >
        ....here goes some logic to render markers
       </MapView>
```
Can u explain me how different this component is from the original MapView? it uses the same props and events?

**Comment by venits** [comment]
Hi @sebackend 

My components takes care of logic related to clustering markers. Your code will not do that.

Currently I am working on new version of my module, so stayed tuned. Current version is not the best option yet. (But it will be 🥇)

I plan to release new version in 2 days.

**Comment by venits** [comment]
Hi, @sebackend  

new version is released 🎉  It is complete rewrite so it may solve some issues but some new issues may appear :) 

If you have time, please test it and let me what do you think.

**And for your questions** -> Yes, it uses same props and events as original MapView.
