### ISSUE TITLE
Rotate Map will Zoom Out

### ISSUE THREAD

**Issue by kkusanagi** [venits/react-native-map-clustering#114]
react-native-map-clustering: 3.0.1
"react-native-maps": "0.25.0"

Both Android and IOS
While rotating, it just keep zoom out. Anyway to avoid zooming out issue? 
Is this react-native-map-clustering issue or not? I may be wrong.

```
<MapView
        mapRef = {(ele)=>{this.mapview_ele = ele;}}
        style={localstyles.map}
        initialRegion={{
          latitude: this.state.latitude,
          longitude: this.state.longitude,
          latitudeDelta: this.maplatitudeDelta,
          longitudeDelta: this.maplongitudeDelta,
        }}
        onRegionChange= {(e)=> {
          this.localCoordinate = e;
          this.maplatitudeDelta = e.latitudeDelta;
          this.maplongitudeDelta = e.longitudeDelta;
        }}
        onClusterPress = {(cluster, children)	=>{
          console.log(cluster, children);
        }}
        showsUserLocation={true}
        showsCompass={true}
        >
        {this.loadMode === 'coordinate' && (<Circle 
          center= {{
            latitude: this.state.mylatitude,
            longitude: this.state.mylongitude, 
          }}
          radius = {this.state.distance_km * 1000}
          fillColor = {'rgba(0,0,0,0.1)'}
        />)}
        {arrMarker}

</MapView>

```

**Comment by venits** [comment]
Hmm it may be issue within my library. I will check it :)

**Comment by venits** [comment]
Hmm ok I have the solution. I will release new version soon.

**Comment by venits** [comment]
Fixed in version **"3.0.2"**.

Remember to always use **initialRegion**.

**Comment by kkusanagi** [comment]
so <MapView region=..... > cannot use?

**Comment by venits** [comment]
You can, but you will have to set up up **onRegionChangeComplete()** in your code and update region every time ;/

**Comment by kkusanagi** [comment]
about this issue is fix. But when i press on cluster. It will rotate back to default direction. Can you remain the map rotation after press the cluster?

**Comment by venits** [comment]
Hmm I use **fitToCoordinates()** from [react-native-maps](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md) to handle **onClusterPress()** and I don't see an option to pass rotation parameter ;/ 

I think it is not possible to prevent rotation :(

**Comment by kkusanagi** [comment]
hmmm... after some checking there is **fitToSuppliedMarkers** & **fitToCoordinates** 
I think both do the same thing (not sure)

If that the case, I think i need to combine **preserveClusterPressBehavior** and  **MapView.animateToRegion()** when cluster is pressed. 
Well, thanks anyway.
