### ISSUE TITLE
Same cluster onClusterPress Unable trigger twice

### ISSUE THREAD

**Issue by kkusanagi** [venits/react-native-map-clustering#115]
"react-native-map-clustering": "^3.0.2",
    "react-native-maps": "0.25.0",

After press on cluster the first time, it trigger the event. 
But after i press the same cluster for second time and above, it DID NOT trigger the event anymore.

**Comment by venits** [comment]
Hi @kkusanagi 

Hmm that is strange because after clicking cluster it should zoom into it, making it disappear ;/

Can you send me code you are using?

**Comment by kkusanagi** [comment]
The cluster on both of the location is exact same, just different floor. 
So even zoom in, it still combine into cluster.

And oh, sometimes the cluster is missing when press.
The cluster location is around 3~5km far from my location.

**Comment by venits** [comment]
Hmm works fine for me ;/ Event triggers every time on cluster, but is not getting declustered because location is the same for two markers.

Can you try below code?
```js
 <MapView
        onClusterPress={(cluster, markers) => console.warn(cluster, markers)}
        initialRegion={{
          latitude: 52.5,
          longitude: 19.2,
          latitudeDelta: 6.5,
          longitudeDelta: 6.5
        }}
        style={{ flex: 1 }}
      >
        <Marker
          coordinate={{
            latitude: 52,
            longitude: 18
          }}
        />
        <Marker
          coordinate={{
            latitude: 52,
            longitude: 18
          }}
        />
</MapView>
```

**Comment by kkusanagi** [comment]
Found the bug.
if you notice, i use latitudeDelta and longitudeDelta to 0.01.
Now, zoom out and find the cluster. 
Once you press on cluster, it will disappeared or cannot press twice when render out the modal.

here use the code below.

<MapView
        preserveClusterPressBehavior
        onClusterPress={(cluster, markers) => {
          this.setState({isGuideModalVisible:true});
          console.warn(cluster, markers);
        }}
        initialRegion={{
          latitude: 52.5,
          longitude: 19.2,
          latitudeDelta: 0.01,
          longitudeDelta: 0.01
        }}
        style={{ flex: 1 }}
      >
        <Marker
          coordinate={{
            latitude: 52,
            longitude: 18
          }}
        />
        <Marker
          coordinate={{
            latitude: 52,
            longitude: 18
          }}
        />
</MapView>
<Modal
          animationType="fade"
          transparent={true}
          visible={this.state.isGuideModalVisible}
          onRequestClose = {()=> {this.setState({isGuideModalVisible:false})}}
        >
          <TouchableWithoutFeedback onPress={()=>{this.setState({isGuideModalVisible:false})}}>
            <View style={{flex:1,backgroundColor:'rgba(0,0,0,0.5)', alignItems:'center',justifyContent:'center'}}>
              <View style={{borderRadius:10,padding:5,alignItems:'center',justifyContent:'center'}}>
                
              </View>
            </View>
          </TouchableWithoutFeedback>
        </Modal>

Maybe mine is too much Marker and it blows up.

**Comment by venits** [comment]
Hmm ok I found a bug :) I will have time to fix it in 4 hours so it should be released in 5.

I will let you know once its done 💪

**Comment by kkusanagi** [comment]
Thanks. I never thought this bug is so hard to find.

**Comment by venits** [comment]
@kkusanagi  I had some free time 🎉 

Please update module version to *3.0.4* and let me know if that will fix your problem ;)

**Comment by kkusanagi** [comment]
Had tested. It is fixed. And strange, it become faster than before. Well, it is a good news too.

**Comment by kkusanagi** [comment]
Oops, the disappearance is fixed. But the press twice issue is still occur. I need to press and move the map and then press the cluster again to trigger the event.

So still not fixed. But better than disappearance.

**Comment by venits** [comment]
Hi, yep I can see this bug. It happens sometimes. Looks like `<Marker/>` **onPress()** method is not called sometimes. It is possible that 2 markers overlap each other.

But don't worry, I have easy fix for it. Will release soon.

**Comment by venits** [comment]
@kkusanagi   Version **3.0.5** is up. 

Let me know if this bug is resolved 👍

**Comment by kkusanagi** [comment]
You just make it worst. Now press the cluster do not focus to it anymore.

**Comment by venits** [comment]
Hmm you tested it on code example above?

**Comment by kkusanagi** [comment]
Yup. Seems like the **preserveClusterPressBehavior** is turn on. The press event do not trigger **fittocoordinate()**

**Comment by venits** [comment]
Hmm ok I see, problem occurs on Android and I only tested it on iOS. I will try ti fix it ASAP.

**Comment by kkusanagi** [comment]
I had tested on IOS and it also occur same issue.

**Comment by venits** [comment]
I reverted changes in version `3.0.6`. For me it looks like problem with **react-native-maps** module.
I only pass **onPress()** prop to marker. I don't have control on when it will call :(

**Comment by kkusanagi** [comment]
hmmm, i try google it and found this. Not sure is this the same issue.

[Marker click event on react native maps not working in react ios
](https://stackoverflow.com/questions/39654594/marker-click-event-on-react-native-maps-not-working-in-react-ios)

**Comment by venits** [comment]
Hmm looks promising will test it.

**Comment by venits** [comment]
Hmm never mind  `Callout` is used for something like this:
<img width="162" alt="Screenshot 2019-11-11 at 20 13 37" src="https://user-images.githubusercontent.com/31382349/68613867-03128a00-04c0-11ea-8d43-8abc539513a8.png">

**Comment by kkusanagi** [comment]
Well, I can't find any solution in google and react-native-map coding.
Seems like no problem and minor problem. 

Haih...Well, this really need some time and much professional tester to get the bugs.
If really react-native-maps issue, we need to create new issue at their github thread.
