### ISSUE TITLE
Migration from react-native-maps-super-cluster

### ISSUE THREAD

**Issue by sebinq** [venits/react-native-map-clustering#116]
Hello! 

I would like to ask you if there is some tutorial for migration tips/tutorial from https://github.com/novalabio/react-native-maps-super-cluster package. Thank you so much!

**Comment by venits** [comment]
Hmm my module is much simpler but it really depends how you code looks right now.

Is it fresh project or something more advanced?

I can help you with refactoring ;)

**Comment by sebinq** [comment]
What about performance comparision? Don't you think it is less effective when the original markers have to be rendered in order to calculate clusters?

**Comment by venits** [comment]
Actually they are no re-rendered. If there is no need for clustering, they will be passed to MapView without editing. I use **React.Children** to do that.
