### ISSUE TITLE
AnimateToRegion ref issue

### ISSUE THREAD

**Issue by djpetenice** [venits/react-native-map-clustering#118]
RN: 0.61.2

I'm trying to get AnimateToRegion to work - I've followed the solutions here but it's not working:

https://github.com/venits/react-native-map-clustering/issues/105
https://github.com/venits/react-native-map-clustering/issues/79

I'm getting the error "Function components can't be give refs. Did you mean to use React.forwardRef() ?"

Anyone know a solution to this?

**Comment by venits** [comment]
Hi, I change implementation a little bit.
Now you have to use **mapRef** instead of **ref**.

Example:
```js
<MapView mapRef={ref => this.mapView = ref} />
```

Let me know if that worked for you :)

**Comment by djpetenice** [comment]
Yep that's worked - thanks for the quick reply 👍

**Comment by thanhluantl2304** [comment]
Should add this to document. It's quite hard to find this solution.

**Comment by venits** [comment]
@thanhluantl2304 

I updated **README.MD** with full code example of how to use `animateToRegion()` 🎉 

https://github.com/venits/react-native-map-clustering#how-to-animate-to-region

**Comment by jakewtaylor** [comment]
@venits Not sure if I've done something wrong, but your example in the README does work, but if using typescript it doesn't infer any types on ref.current, so throws a type error:
```TS
export const Example = forwardRef<Handle, Props>((props, ref) => {
  const mapRef = useRef<MapView>(null);
  const userLocation = useUserLocation();

  const recenter = useCallback(() => {
    if (userLocation && mapRef.current) {
      // Error on animateCamera (see screenshot below)
      mapRef.current.animateCamera({ ... });
    }
  }, [userLocation]);

  useImperativeHandle(ref, () => ({ recenter }));

  return (
    <MapView
      style={{ flex: 1 }}
      ref={mapRef}
      showsUserLocation
      initialRegion={{
        ...userLocation,
        latitudeDelta: 1,
        longitudeDelta: 1,
      }}
    />
  );
});
```

![image](https://user-images.githubusercontent.com/8126758/83152520-cfaeea00-a0f5-11ea-935b-c36e75eab626.png)

Getting round this with a `// @ts-ignore` for now 😄
