### ISSUE TITLE
version 1.2, lost custom marker images

### ISSUE THREAD

**Issue by Werbelow** [venits/react-native-map-clustering#12]
Love this library, its exactly what I need, however, I happen to check the repo and saw that 1.2 was out, so I upgraded, however, I have custom marker images as a child to <Marker> showing a users avatar once zoomed in enough. 

After switching to 1.2, all the custom images missing and instead it just showed the red pin icon. 

So far I have just downgraded back to 1.1.6 and that seems to be working fine. 

Thanks again for this library :)

**Comment by venits** [comment]
Hi, 
Thank you so much for pointing this error, I was missing few lines ;)

Everything should work now in version 1.2.1.

I highly recommend update to version >= 1.2.0 because of new algorithm that is much faster.

**Have a great day and Happy Coding :)**
