### ISSUE TITLE
how to use mapRef with useRef hook

### ISSUE THREAD

**Issue by dragma** [venits/react-native-map-clustering#120]
Hello, 
I can't find a way to use the function props `mapRef` with the `useRef` hook.
Help ? :)
Regards,
F.

**Comment by venits** [comment]
Hmm looks like:

```js
 mapRef={ref => (mapRef = ref)}
```

is the only way ;/

It works that way because my component uses **createRef()** inside and I only call **mapRef()** as side effect.

**Comment by dragma** [comment]
Unfortunaetly, we can't reassign a ref. If we try to do this, an error pops up.
I maanged to do the trick that way 

```
const mapRef = useRef(null);
[...]
<MapView
  mapRef={(ref) => { mapRef.current = ref; }}
  ...
/>
```

A dirty workaroud, but a workaroud anyway ! :)

Thanks !
