### ISSUE TITLE
How to achieve Spiderfier when I have multiple marker at the same location?

### ISSUE THREAD

**Issue by meconit** [venits/react-native-map-clustering#122]
I want result similar to this when I have markers at the same location, I have 30+ marker with same coordinates and cluster is not expanding after that. Cluster keep showing 32 when I click on cluster.

This is the result I want:
![spiderfier](https://user-images.githubusercontent.com/58064527/71569178-41f1b300-2af3-11ea-96cb-e2ae65d1d6f3.PNG)

Is this possible? If not then what are the other options?

**Comment by chetanparmar95** [comment]
This issue was submitted by me: I could achieve similar to this and opened a [pull request](https://github.com/venits/react-native-map-clustering/pull/123) for the same.

**Comment by venits** [comment]
New version of module `3.1.2` is live with Spiderfier support 👍 

Thank you again for such a great work :)
