### ISSUE TITLE
onClusterPress does not returns right number of markers

### ISSUE THREAD

**Issue by harishchopra86** [venits/react-native-map-clustering#124]
onClusterPress always returns markers numbers = 10 if number is great than 10.
If the markers number is less than 10 then it returns the right value.
So the issue only comes when number of markers is create than 10 in the cluster.

**Comment by chetanparmar95** [comment]
@harishchopra86 You will get the right number of markers in the next version. I've opened a pull request with new feature that includes this, and this might get merged by end of this week. :)

**Comment by harishchopra86** [comment]
Sounds good.
Thanks @chetanparmar95

**Comment by venits** [comment]
Fixed in version `3.1.2` 🎉
