### ISSUE TITLE
renderCluster example

### ISSUE THREAD

**Issue by Anytram** [venits/react-native-map-clustering#128]
Hello 
I have problem with renderCluster props. I try to pass function that returns custom cluster marker view but it didn't render on map.
Maybe someone could give me example how to implement this. I could done something in the wrong way.

**Comment by venits** [comment]
Hi @Anytram 

Here is full code example:

```js
import React from "react";
import { View, Text } from "react-native";
import MapView from "react-native-map-clustering";
import { Marker } from "react-native-maps";

const INITIAL_REGION = {
  latitude: 52.5,
  longitude: 19.2,
  latitudeDelta: 8,
  longitudeDelta: 8
};

const App = () => (
  <MapView
    initialRegion={INITIAL_REGION}
    style={{ flex: 1 }}
    renderCluster={cluster => {
      const { id, geometry, onPress, properties } = cluster;
      const points = properties.point_count;

      return (
        <Marker
          key={`cluster-${id}`}
          coordinate={{
            longitude: geometry.coordinates[0],
            latitude: geometry.coordinates[1]
          }}
          onPress={onPress}
        >
          <View style={{ padding: 16, backgroundColor: "white" }}>
            <Text>{points}</Text>
          </View>
        </Marker>
      );
    }}
  >
    <Marker coordinate={{ latitude: 52.0, longitude: 18.2 }} />
    <Marker coordinate={{ latitude: 52.2, longitude: 18.3 }} />
  </MapView>
);

export default App;
```

Let me know if that clear things up for you 👍

**Comment by Anytram** [comment]
Hi,
works almost perfectly, unfortunately individual markers are on top and sometimes cover framgent of the cluster marker: /

**Comment by venits** [comment]
@Anytram try playing with `zIndex` for clusters and markers. It should work :)

**Comment by Anytram** [comment]
Yes, it works, thank you very much!

**Comment by DmitriyO** [comment]
Hi, after struggling with the same issue and the finding a great example here, I can suggest to add this example in the main page, this will make using this great library much easier :)

**Comment by DiorAbjalilov** [comment]
Thanks. it works for me
