### ISSUE TITLE
Alternative to onRegionChange

### ISSUE THREAD

**Issue by brianlaw033** [venits/react-native-map-clustering#13]
Since I cannot use onRegionChange here
Any idea how can I do something when I pan over the map?

Also how can I get the region if I need it in my state?

**Comment by venits** [comment]
Hi,
you can use onRegionChange, you only can't use onRegionChangeComplete by default (but there is also a way to use it).
If you want to get current region just do that:
```javascript
<MapView
    onRegionChange={state => console.warn(state.longitude)}
    ...
</MapView>
```

**Comment by brianlaw033** [comment]
sorry my bad, what I meant was `onRegionChangeComplete`
but why can't I do `onRegionChange={state => this.setState({ region: state  })}`
if I do like that, the map will always go back to the initial point
