### ISSUE TITLE
Change the prop clusteringEnabled dynamically dont work

### ISSUE THREAD

**Issue by aHandToHelp** [venits/react-native-map-clustering#138]
When i didn need to cluster any more i change the prop clusteringEnabled to false
but the clusters are still showing besides that the marker are no more.

Any ideas?

**Comment by abegehr** [comment]
Having the same issue. We want to disable clustering for zoom levels larger than a constant.
@venits, do you have an idea?

**Comment by wesvance** [comment]
In my case, I was trying to enable clustering when the results on the map exceeded 200 markers. Using clusteringEnabled with a variable was not working - but I was able to set maxZoom to 0 and achieved the same effect. 
```
<MapView
maxZoom={markersOnMap.length > 200 ? 12 : 0}/>
```

**Comment by venits** [comment]
Fixed in module version `3.2.0`

Thank you for your contribution ❤️
