### ISSUE TITLE
Customize markers in spiral view

### ISSUE THREAD

**Issue by AFMW** [venits/react-native-map-clustering#139]
Is there a way for customizing the markers in the spiral view?, I'm trying to customize them but nothing have worked yet.

My code:
`<MapView  mapRef={ref => this.map = ref}
                                             style={{
                                                  position: 'absolute',
                                                  top: 0,
                                                  left: 0,
                                                  right: 0,
                                                  bottom: 0
                                              }} 
                                              initialRegion={this.state.regionLocal}
                                              showsUserLocation={true}
                                              showsPointsOfInterest={true}
                                              showsBuildings={true}
                                              showsMyLocationButton={false}
                                              mapType={this.state.tipoMapa}
                                              loadingEnabled={true}
                                              clusterColor={"#140c98"}
                                              radius={30}
                                              maxZoom={30}
                                              onRegionChangeComplete={ (region) => {
                                                this.setState({regionLocal:region})
                                            }} >
                                                    {this.state.inmuebles.map((item,index) => {`
                                                       
                                                        var precio=0
                                                        if (item.transaccion_inmueble=="Venta") {
                                                            precio=this.abbrNum(item.precio_venta,2)
                                                        }else if (item.transaccion_inmueble=="Arriendo") {
                                                            precio=this.abbrNum(item.precio_renta,2)
                                                        }else{
                                                            precio=this.abbrNum(item.precio_venta,2)
                                                        }
                                                        var contador = 0
                                                        for (var i = 0; i < this.state.inmuebles.length; i++) {
                                                            if (item.longitud==this.state.inmuebles[i].longitud && item.latitud==this.state.inmuebles[i].latitud ) {
                                                                contador++

                                                            }
                                                        }
                                                                return <Marker ref={"marker"} key={`${index}-${item.selectedMarker==true ? 'active' : 'inactive'}`} tracksViewChanges={ false } coordinate={{latitude: item.latitud,longitude: item.longitud}} onPress={()=>{
                                                                    item.selectedMarker=true
                                                                    this.setState({dataInmuebleModal:item,indexInmuebleModal:index})
                                                                    this.map.animateToRegion({latitude:item.latitud,longitude:item.longitud,latitudeDelta: 0.1022/10,longitudeDelta: 0.0521/10})
                                                                    this.refs.modalDetalleMapa.open()
                                                                    this.animateDetailTo1();

                                                                }}>
                                                                    <View style={{backgroundColor: item.selectedMarker==true? '#140c98' : '#f41b4e', padding: 3, borderRadius:4,borderWidth:1,borderColor:item.selectedMarker==true? '#140c98' : '#f41b4e'}}>
                                                                       <Text style={{fontSize:13, color:'white', fontFamily:'Roboto-Regular',}}>{precio}</Text>
                                                                    </View>
                                                                    <View style={{backgroundColor:item.selectedMarker==true? '#140c98' : '#f41b4e',borderColor:item.selectedMarker==true? '#140c98' : '#f41b4e',borderTopWidth:0,borderBottomWidth:1,borderLeftWidth:1,borderRightWidth:0, height:10,width:10,zIndex:9999999,alignSelf:'center',bottom:5, transform: [{ rotate: '45deg'}]}}>
                                                                    </View>
                                                                </Marker>
                                                    })
                                                    }
                                    </MapView>
`

**Comment by letmagnino** [comment]
I have the same problem.

**Comment by nashashibi** [comment]
`<Marker image={require('your-image.png')} ...otherProps />`

**Comment by CompRider** [comment]
I have same problem, my custom marker contain text and image but it's not working.

**Comment by venits** [comment]
Fixed in module version `3.2.0`

Thank you for your contribution ❤️
