### ISSUE TITLE
renderCluster Improvement

### ISSUE THREAD

**Issue by Samnan** [venits/react-native-map-clustering#142]
Hi, First it's a great component, very fast rendering and actually helped speed up my map view.
I am having one issue. I need to render the cluster not just based on the count of the markers within that cluster, I need to access the individual properties of each of my customer marker component within the cluster so that I can decide how they display as a cluster. Is there an example of suggestion on how can i get all the markers and iterate through them when rendering them as a cluster?

**Comment by venits** [comment]
Hi @Samnan 

In version `3.3.3` I added support for `superClusterRef` prop that gives you easy access to [supercluster](https://github.com/mapbox/supercluster) instance.

This is example how to use it:
```js

import React, { useRef } from "react";
import MapView from "react-native-map-clustering";

const App = () => {
  const superCluster = useRef();

  return <MapView superClusterRef={superCluster}>
    {/* markers */}
  </MapView>;
};

export default App;
```

If you want to get all markers inside cluster you can call a function like this:
```js
  const markers = superCluster.current.getLeaves(cluster.id, Infinity);
```

If you want to get markers and then render cluster you should use `renderCluster` prop.

Here is how you can use it:

```js
import React, { useRef } from "react";
import MapView from "react-native-map-clustering";
import { Marker } from "react-native-maps";

const App = () => {
  const superCluster = useRef();

  return (
    <MapView
      renderCluster={(cluster) => {
        const { geometry, onPress, id } = cluster;

        const markers = superCluster.current.getLeaves(id, Infinity);
        console.warn(markers);  // here you can find properties of your markers

        return (
          <Marker
            key={`${geometry.coordinates[0]}_${geometry.coordinates[1]}`}
            coordinate={{
              longitude: geometry.coordinates[0],
              latitude: geometry.coordinates[1],
            }}
            onPress={onPress}
          />
        );
      }}
      superClusterRef={superCluster}
    >
      {/* markers */}
    </MapView>
  );
};

export default App;

```

**Comment by Samnan** [comment]
@venits thats awesome. I am currently using an alternate solution for clustering, but as soon as i get a chance, i will come back to this.

Thanks for the good work. Keep it up!
