### ISSUE TITLE
Function components cannot be given refs

### ISSUE THREAD

**Issue by maartenvandillen** [venits/react-native-map-clustering#144]
I am getting the following warning:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
    in ClusteredMapView`

Does anybody know how to fix this?

**Comment by Cimera42** [comment]
I got this when I was using `ref` with `MapView` from `react-native-map-clustering`. Fixed by changing to `mapRef`.

**Before:**
 `ref={ref => mapRef.current = ref}`

**After:**
`mapRef={ref => mapRef.current = ref}`

**Comment by riccardolardi** [comment]
I'm getting `restProps.mapRef is not a function` when I try fixing this as described in https://github.com/venits/react-native-map-clustering/issues/144#issuecomment-607918679 - any hints?

**Comment by askpatrickw** [comment]
I wanted to give another before and after. I had a functioning app where I was using this.map to do a lot of things.. All I had to do was the make the change @Cimera42 mentioned and most all the things work as before.

## Before
```javascript
<MapView
  ...
  ref={ref => {
              this.map = ref;
            }}
...
>
```

## After
```javascript
<MapView
  ...
  mapRef={ref => {
              this.map = ref;
            }}
...
>
```

**Comment by venits** [comment]
Yep,

changing `ref` to `mapRef` solves the issue :)

**Comment by GunnarAK** [comment]
@venits what is the reason behind removing `mapRef` from v3.3.3?

**Comment by venits** [comment]
@GunnarAK  Using `ref` is more obvious and it is recommended approach in React. 

Please look at this discussion: https://github.com/venits/react-native-map-clustering/pull/158/files

Since there is a lot of confusion, I am going to bring back `mapRef` in few hours. It will be available in version `3.3.4`.

**Comment by askpatrickw** [comment]
Makes a lot of sense to use ref if you want the HOC to be a drop in replacement for MapView.

**Comment by askpatrickw** [comment]
Makes a lot of sense to use ref if you want the HOC to be a drop in replacement for MapView.

**Comment by venits** [comment]
The version `3.3.4` is up with `mapRef` prop back.

Now both `ref` and `mapRef` will work as expected.

I would recommend switching to `ref` and `useRef` for more universal code 👍
