### ISSUE TITLE
Access the package's component using ref

### ISSUE THREAD

**Issue by nikhilkumar6** [venits/react-native-map-clustering#148]
Hi, I want to get the leaves by clusterId. I saw the code and it seems the only way to access the leaves is by **onClusterPress** method. I want to access the leaves without having to click on the cluster marker. Is there any way to do so? 

I tried adding ref prop to the component but it didn't work.

The clusterEngine should be accessible as it is in the 'react-native-maps-super-cluster' package. It can either by by ref or by exposing a function that would return the cluster engine variable. It will help to access and get the properties directly in case it's not exposed by the package.

Request the contributor to add the functionality.

**Comment by venits** [comment]
Hi @nikhilkumar6 

In version `3.3.3` I added support for `superClusterRef` prop that gives you easy access to [supercluster](https://github.com/mapbox/supercluster) instance.

This is example how to use it:
```js

import React, { useRef } from "react";
import MapView from "react-native-map-clustering";

const App = () => {
  const superCluster = useRef();

  return <MapView superClusterRef={superCluster}>
    {/* markers */}
  </MapView>;
};

export default App;
```

If you want to get all markers inside cluster you can call a function like this:
```js
  const markers = superCluster.current.getLeaves(cluster.id, Infinity);
```

Thank you for contributing 💖
