### ISSUE TITLE
wrapping makers in other component

### ISSUE THREAD

**Issue by MebDevelop** [venits/react-native-map-clustering#149]
My Code looks like this and it's not showing clusters.
```
<MapView
        mapRef={(ref) => mapRef = ref}
        showsUserLocation
        showsMyLocationButton={true}
        style={{ flex: 1, width, height }}
        initialRegion={{
          latitude,
          longitude,
          latitudeDelta: LATITUDE_DELTA,
          longitudeDelta: LONGITUDE_DELTA
        }}
        scrollEnabled={scrollEnabled}
        onPanDrag={e => onPanDrag(e)}
      >
        
        <Markers/>
</MapView>
```

```
<View>
  {
        locations.map((location) => {
           return (
            <Marker
              identifier={location.properties.Id}  // used for "Show on map"
              key={location.properties.Id}
              ref={id => pinRef = id}
              title={name}
              pinColor={color}
              coordinate={{ latitude, longitude }}
              {...(my_trip && { image: car })}
              stopPropagation={true}
            >
              <Callout pointerEvents="auto"  onPress={() => {
                setInfoWindowVisible(true, location);
              }}>
                <CustomCalloutView name={name} address={address}/>
              </Callout>
            </Marker>
      );
  })}
</View>
``` 
any ides on this?

**Comment by venits** [comment]
If `<Markers/>` is the second code block then this syntax is incorrect.

Don't map markers in `<View/>` include them directly in MapView.

**Comment by MebDevelop** [comment]
Thank you. so no way with second code block?
I tried with <> </>, it's not working too.

**Comment by nashashibi** [comment]
@venits' solution should technically work, if it didn't, try this:

```
<MapView ...someProps>
{
  locations.map((location) => {
    return (
      <YourCustomMarker
         key={location.properties.Id}
         location={location}
      />
    )
  }
}
</MapView>
```


then **YourCustomMarker** component can return this (remember to pass down any other needed props):
```
<Marker
  identifier={location.properties.Id}  // used for "Show on map"
  // key={location.properties.Id} // not needed anymore here
  ...
  ...
  ...
</Marker>
```

**Comment by hiteshAr** [comment]
Hello @venits!

First of all, thanks a lot for this amazing library. It is helping me a lot to optimise the Map performance on the Android and iOS with so many custom markers.
I am also having some similar issues. I need to display Markers Clusters with some other components as well. For example, user's current location with the custom Marker, a polyline between 2 markers etc. Can you please suggest a way to do that?

I am having an e-commerce application with the order tracking where I have to show the Stores(with clusters), user's current location and the path between user's current location and a Location on a map.

Currently, I am only able to place the markers on the Map. If I try to place the other components on the map, the clustering does not work.

**Comment by SirPhemmiey** [comment]
Hey @venits @hiteshAr any update on this, please?

**Comment by SirPhemmiey** [comment]
Clustering doesn't work when i wrap markers in another component also. 

@venits @hiteshAr @nashashibi

**Comment by paolosantarsiero** [comment]
Any updating to show a polylines clustering?

**Comment by paolosantarsiero** [comment]
`{lines.map((data)=> <Polyline identifier={`line-${data.id}`} key={data.id || Math.random()} coordinate={data.location1} coordinates={[data.location1,data.location2]} onPress={()=>console.log("CLICK POLYLINE")}  strokeWidth={4} tappable={true}/>)}
`

**Comment by alexis-regnaud** [comment]
I have the same problem on my side. Everything works well when I have `Marker` directly put within the `MapView` :

```
<MapView>
    {items.map (()) => <Marker>...</Marker> }
</MapView>
```

But as soon as I put the Mark within another custom component, the cluster doesn't appear anymore (And all markers seems slower) :

```
function Map() {
   return (
       <MapView>
           {items.map (()) => <CustomMarker> }
      </MapView>
   )
}

...

function CustomMarker() {
   return <Marker>...</Marker>
}
```

**Comment by alexis-regnaud** [comment]
Seems like the issue is still related to #137 because the add coordinate to my CustomMarker's props (Before it was passed directly as primitive props: `latitude={coordinate .latitude} longitude={coordinate.longitude}`) and now I see the clusters. The map + the pins (Markers + clusters) are however slower to make a first render in compare to when I don't have a `CustomMarker`
