### ISSUE TITLE
Cannot scroll map on iOS

### ISSUE THREAD

**Issue by ewein** [venits/react-native-map-clustering#15]
I'm using react-native-maps through Expo for my app with your clustering module however on iOS the map is not able to scroll. All the markers and everything show up correctly but the map does not move around.  Any help would be appreciated. Below is my map code.

```javascript                
               <MapView
                    clusterColor="#FB4F94"
                    clusterTextColor="#fff"
                    clusterBorderColor="#F86048"
                    clusterBorderWidth={0}
                    region={{
                        latitude: 52.5,
                        longitude: 19.2,
                        latitudeDelta: 6.5,
                        longitudeDelta: 6.5
                    }}
                    style={styles.mapView}
                >
                    {
                        this.state.markers.map((marker, i) => {
                            return (
                                <Marker
                                    key={i}
                                    onPress={this._show.bind(this, marker.image)}
                                    coordinate={{ latitude: marker.latitude, longitude: marker.longitude }}
                                >
                                    <Image
                                        source={{uri: marker.image}}
                                        style={styles.markerImage}
                                    />
                                </Marker>
                            )
                        })
                    }
                </MapView>
```

I believe changing the 'region' prop to 'initialRegion' when you creacte the react-native-maps component will fix the issue so I have submitted a PR.

**Comment by venits** [comment]
Hi,
Expo for sure isn't friendly for things like map, so I don't really recommend using it. If you can, just create new project without using Expo and everything will work fine but If you really want to use Expo I will try to fix this.

So my first question:

Is it like, you can scroll on map but after releasing touch map goes to initial region or you just can't scroll on map at all?

**Comment by ewein** [comment]
You can't scroll on map at all. The map loads with all the markers
correctly but you can't interact with the map at all. Its working fine on
Android so this issue is only on iOS.

**Comment by venits** [comment]
Hmm I am not sure if it is a module fault. Please use MapView from "react-native-maps" and test if scroll works there.

**Comment by ewein** [comment]
It works fine if I just use react-native-maps.

**Comment by venits** [comment]
Hmm do you test it on emulator only? If so please check on real device if you can.

**Comment by ewein** [comment]
no I have only tested on a real device (IPhone 6S).

**Comment by venits** [comment]
Hmm it's really strange. My only idea right now is that there might be something wrong with Expo. You can create app using **react-native init ProjectName** and run without Expo. Same code and everything just without Expo.

**Comment by ewein** [comment]
I'm using Expo to build to both Android and iOS, I can't not switch of
Expo. The app was created with create-react-native-app which has Expo
integrated into it.

**Comment by ewein** [comment]
I know react-native-maps had issues with scrolling on iOS when the region
prop was set and not the initialRegion pop.

**Comment by venits** [comment]
Hmm if you can please go to this directory:

**node_modules/react-native-map-clustering/MapView/MapWithClustering.js**

And add this, below line number 166:

        initialRegion={this.state.region}

Maybe you are right and It will help. Please tell me your result :)

**Comment by venits** [comment]
In version 1.2.3 I added initialRegion so that should work now :)

**Comment by ewein** [comment]
Were other changes made? Version 1.2.3 doesn't seem to work at all for iOS
and Android? I managed to get the iOS map working on version 1.2.0 by
playing with the styles a bit so it might have been a style issue on iOS.

**Comment by ewein** [comment]
Do you have a fix for this issue using your package. I am experiencing this
issue using v1.2.8.
https://github.com/airbnb/react-native-maps/issues/1652

**Comment by ewein** [comment]
Nevermind I see the documentation has been updated as well. It's all
working as intended. One thing though, is there a way to set some value so
when you zoom in to a certain depth the cluster will expand all the
markers. Right now if you have two markers right beside each other they are
always clustered even if you zoom all the way in. Any thoughts?

**Comment by venits** [comment]
There is really not much module can do. 
Of course I can add custom check especially for this case but it is not something library should do because 1 for 1000 people will use it and it will impact performance.

I recommend to check onClusterPress and maybe there add information for user that we have 2 places here. Or just change coordinates of one marker so on certain zoom level markers will split.

If it will be big issue for you and you have to complete that for example for your job.
Fork this module and let me know I will make pull request that will add code you need.

**Comment by ewein** [comment]
Ok cool, I tried just using the onClusterPress but there seems to be an
issue with that in the latest version. The callback is fired however there
are no coords or markers returned and it seems after that callback is fired
no other onPress events work. Any ideas?

**Comment by venits** [comment]
Hmm for me it seems that you made some error in callback function. Please show me your code for onClusterPress and function in it.

**Comment by ewein** [comment]
Hey the only thing I'm doing in the callback is alerting 'hello' this works
and printing the coordinates, however no coordinates are printed and after
that no click events work and the clustering stops working.

**Comment by venits** [comment]
There must be something wrong with your code because I checked onClusterPress and everything works as expected. Please try to make new project and do everything as it's said in README.md or send me source code so I can have look at it.

**Comment by ewein** [comment]
The cluster click code is very straight forward so I'm not sure how that
could be causing issues. Here is the full component code:

import React, { Component } from 'react';
import { connect } from 'react-redux';
import MapView from 'react-native-map-clustering';
import { Marker } from 'react-native-maps';
import Expo, { Location, Permissions } from 'expo';
import { StyleSheet, View, Image, TouchableOpacity  } from 'react-native';
import { Form, Item, Input, Label, Footer, FooterTab, Icon, Badge,
Button, Text, Spinner } from 'native-base';

import { loadProfile } from '../../actions/user';
import ViewPost from '../viewPost';
import Filters from './filters';
import Camera from '../camera';
import Profile from '../profile';
import Notifications from './notifications';

class Map extends Component {
    constructor(props) {
        super(props);
        this.state = {
            showPost: false,
            showCamera: false,
            showProfile: false,
            showNotifications: false,
            post: false,
            showFilters: false,
            userLocation: false,
            hasCameraPermission: null,
            region: {
                latitude: 49.8741745,
                longitude: -119.5477186,
                latitudeDelta: 6.5,
                longitudeDelta: 6.5
            }
        };

        this._takePicture = this._takePicture.bind(this);
        this._closePost = this._closePost.bind(this);
        this._showPost = this._showPost.bind(this);
        this._goToProfile = this._goToProfile.bind(this);
        this._toggleFilters = this._toggleFilters.bind(this);
        this._toggleCamera = this._toggleCamera.bind(this);
        this._toggleProfile = this._toggleProfile.bind(this);
        this._toggleNotifications = this._toggleNotifications.bind(this);
        this._onRegionChange = this._onRegionChange.bind(this);
        this._onClusterClick = this._onClusterClick.bind(this);
    }

    async componentWillMount() {
        this._getLocationAsync();
        Expo.ScreenOrientation.allow(Expo.ScreenOrientation.Orientation.ALL);
        const { status } = await Permissions.askAsync(Permissions.CAMERA);
        this.setState({ hasCameraPermission: status === 'granted' });
    }

    componentDidMount() {
        if (this.props.posts) {
            this.setState({
                region: {
                    latitude: (this.props.posts.markers.length === 0)
? 49.8741745 : +this.props.posts.markers[0].latitude,
                    longitude: (this.props.posts.markers.length === 0)
? -119.5477186 : +this.props.posts.markers[0].longitude,
                    latitudeDelta: 6.5,
                    longitudeDelta: 6.5
                }
            });
        }
    }

    timerForMap = setTimeout(()=>{}, 1000);

    _getLocationAsync = async () => {
        let { status } = await Permissions.askAsync(Permissions.LOCATION);
        if (status !== 'granted') {
            alert('Permission to access location was denied.');
            return;
        }

        let userLocation = await Location.getCurrentPositionAsync({});
        this.setState({ userLocation });
    };

    _takePicture = () => {
        if (this.state.hasCameraPermission) {
            this._toggleCamera();
        } else {
            alert('No permission to use camera.');
        }
    };

    _goToProfile = () => {
        this.props.dispatch(loadProfile('private', this.props.user.id,
this._toggleProfile));
    };

    _showPost = (post) => {
        this.setState({
            showPost: true,
            post
        });
    };

    _closePost = () => {
        this.setState({
            showPost: false,
            post: false
        });
    };

    _onClusterClick = (coordinates, markers) => {
        alert('Cluster Clicked');
        console.log(coordinates);
        console.log(markers);
    };

    _toggleFilters = () => {
        this.setState({ showFilters: !this.state.showFilters });
    };

    _toggleCamera = () => {
        this.setState({ showCamera: !this.state.showCamera });
    };

    _toggleProfile = () => {
        this.setState({ showProfile: !this.state.showProfile });
    };

    _toggleNotifications = () => {
        this.setState({ showNotifications: !this.state.showNotifications });
    };

    _onRegionChange = (region) => {
        clearTimeout(this.timerForMap);
        this.timerForMap = setTimeout(()=>{
            this.setState({ region })
        },500);
    };

    render() {
        if (!this.props.posts || !this.props.user) {
            return <Spinner />
        }

        if (this.state.showPost) {
            return <ViewPost
                id={this.state.post.id}
                handleClose={this._closePost}
                navigation={this.props.navigation}
                dispatch={this.props.dispatch}
            />;
        }

        if (this.state.showCamera) {
            return <Camera toggleCamera={this._toggleCamera} />;
        }

        if (this.state.showFilters) {
            return <Filters toggle={this._toggleFilters} />
        }

        if (this.state.showProfile) {
            return <Profile
                navigation={this.props.navigation}
                goBack={this._toggleProfile}
            />
        }

        if (this.state.showNotifications) {
            return <Notifications
                navigation={this.props.navigation}
                toggleProfile={this._toggleProfile}
                goBack={this._toggleNotifications}
            />
        }

        return (
            <View style={styles.container}>
                <MapView
                    clustering={true}
                    clusterColor="#FB4F94"
                    clusterTextColor="#fff"
                    clusterBorderColor="#F86048"
                    clusterBorderWidth={0}
                    region={this.state.region}
                    onRegionChange={this._onRegionChange}
                    onClusterPress = {this._onClusterClick}
                    style={styles.mapView}
                >
                    {
                        this.props.posts.markers.map((marker, i) => {
                            return (
                                <Marker
                                    key={i}
                                    onPress={() => {
this._showPost(this.props.posts.posts[marker.id])}}
                                    coordinate={{ latitude:
+marker.latitude, longitude: +marker.longitude }}
                                >
                                    <Image
                                        source={{uri: marker.thumbnail}}
                                        style={styles.markerImage}
                                    />
                                </Marker>
                            )
                        })
                    }
                </MapView>
                <View style={{ position: 'absolute', top:0, alignSelf:
'center' }}>
                    <Image
                        source={require('../../assets/logo.png')}
                        style={styles.logo}
                    />
                </View>
                <Footer style={{ position: 'absolute', bottom:0,
backgroundColor: 'transparent' }}>
                    <FooterTab style={{ backgroundColor: 'rgba(255,
255, 255, 0.7)' }}>
                        <Button vertical>
                            <TouchableOpacity onPress={this._toggleFilters}>
                                <Icon name="flask" style={{color:'#707070'}}/>
                            </TouchableOpacity>
                        </Button>
                        <Button vertical>
                            <TouchableOpacity onPress={this._takePicture}>
                                <Icon name="ios-camera"
style={{color:'#707070'}} />
                            </TouchableOpacity>
                        </Button>
                        {
                            this.props.user.notifications.unseen > 0 ?
                                <Button badge vertical>
                                    <TouchableOpacity
style={{height:'100%', justifyContent:'center', alignSelf:'center'}}
onPress={this._toggleNotifications}>
                                        <Badge
style={{backgroundColor: '#FB4F94'}}><Text>{
this.props.user.notifications.unseen }</Text></Badge>
                                        <Icon name="ios-notifications"
style={{color:'#707070'}} />
                                    </TouchableOpacity>
                                </Button>
                                :
                                <Button vertical>
                                    <TouchableOpacity
onPress={this._toggleNotifications}>
                                        <Icon name="ios-notifications"
style={{color:'#707070'}} />
                                    </TouchableOpacity>
                                </Button>
                        }
                        <Button vertical>
                            <TouchableOpacity onPress={this._goToProfile}>
                                <Icon name="md-person"
style={{color:'#707070'}} />
                            </TouchableOpacity>
                        </Button>
                    </FooterTab>
                </Footer>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
        justifyContent:'center'
    },
    customCluster: {
        backgroundColor: 'blue',
        borderRadius: 10
    },
    markerImage: {
        width: 30,
        height: 30,
        borderRadius: 5
    },
    mapView: {
        flex: 1
    },
    logo: {
        width: 300,
        height: 200,
        marginTop: -50
    },
    footerText: {
        fontSize: 8
    },
    cameraView: {
        flex: 1,
        backgroundColor: 'transparent',
        flexDirection: 'row',
    }
});

const mapStateToProps = state => ({
    user: state.user.data,
    posts: state.posts.all
});

export default connect(
    mapStateToProps,
)(Map);

**Comment by ewein** [comment]
The issue seems to be the onRegionChange, if I remove that it works as
expected.

**Comment by ewein** [comment]
It works but still only coordinates are available, not the markers object.

**Comment by ewein** [comment]
Yeah so that was on version 1.2.0 on the latest version 1.2.8 the
onClusterClick is not working, nothing is returned in the callback.

**Comment by ewein** [comment]
Ok so on version 1.2.8 works if I only put in the coords param and not the
markers:

This does work:

<MapView
    clustering={true}
    clusterColor="#FB4F94"
    clusterTextColor="#fff"
    clusterBorderColor="#F86048"
    clusterBorderWidth={0}
    region={this.state.region}
    onRegionChange={this._onRegionChange}
    onClusterPress = {(coords) => {
        console.log(coords);
    }}
    style={styles.mapView}
>


This does not work:

<MapView
    clustering={true}
    clusterColor="#FB4F94"
    clusterTextColor="#fff"
    clusterBorderColor="#F86048"
    clusterBorderWidth={0}
    region={this.state.region}
    onRegionChange={this._onRegionChange}
    onClusterPress = {(coords, markers) => {
        console.log(coords);
        console.log(markers);
    }}
    style={styles.mapView}
>
