### ISSUE TITLE
Multiple spirals & Spiral with a custom marker

### ISSUE THREAD

**Issue by CompRider** [venits/react-native-map-clustering#155]
Hi thanks for this wonderful library but I am stuck at some points and can't do anything.
**Issue 1 - Multiple spirals:** Cluster not expanding into a spiral if multiple markers are available
**Issue 2 - Spiral with a custom marker:** I have a custom marker with children and it is not displayed in a spiral view.

I tried some open PR's but not helpful.

Please help me.
Thanks in advance.

**Comment by venits** [comment]
I released new version of this module `3.2.0`

Please try it now and let me know if that works for you.

**Comment by CompRider** [comment]
Hi @venits thanks for the update but now getting a new issue.

**Issue: Duplicate markers in multiple spirals** 

ClusteredMapView.js 
`let positions = generateSpiral(marker, clusterChildren);`

helpers.js
`for (let i = 0; i < count; i++) {
    angle = 0.25 * (i * 0.5);
    let latitude = centerLocation[1] + 0.0002 * angle * Math.cos(angle);
    let longitude = centerLocation[0] + 0.0002 * angle * Math.sin(angle);
    res[i] = {
      index: clusterChildren[i].properties.index,`

always start `i` from 0 `clusterChildren[i]` so getting duplicate in multiple spirals

Marker having a proper latitude and longitude but wrong marker child.

**Comment by venits** [comment]
Hi @CompRider 

can you update module version to `3.3.3` and test it again?

I made some changes that should resolve this issue 👍
