### ISSUE TITLE
Duplicate marker 

### ISSUE THREAD

**Issue by CompRider** [venits/react-native-map-clustering#159]
Hi @venits thanks for the new release :)

I found the following issue in the latest release.

**Issue: Duplicate marker** If I having spiral and on max zoom, I am getting duplicate marker.

<img width="159" alt="Screenshot 2020-05-12 at 5 40 25 PM" src="https://user-images.githubusercontent.com/7301527/81689221-b6f8d000-9477-11ea-846b-4103a190086f.png">

I think this is happening because of these markers are available in `spiderMarkers` and in `markers` on max zoom `marker.properties.point_count === 0` is getting true so displayed one time and already available in `spiderMarkers` so spiral is also visible.

Hope it will be helpful to resolve this issue.

**Comment by CompRider** [comment]
@venits I have created #160  PR for this issue, please review.

**Comment by venits** [comment]
@CompRider Thank you so much for spotting that ❤️ 

I released version `3.3.5` with that change 👍
