### ISSUE TITLE
Incorrect Marker prop

### ISSUE THREAD

**Issue by alexeymolchan** [venits/react-native-map-clustering#161]
Hi, you are passing tracksClusterViewChanges prop to react-native-maps Marker component, but Marker actually accept tracksViewChanges prop.

So, i suppose this issue should be reopened https://github.com/venits/react-native-map-clustering/issues/133

https://github.com/venits/react-native-map-clustering/blob/262dd27428813ddc8128f8c361e60888082ac8a6/lib/ClusteredMarker.js#L27

**Comment by venits** [comment]
Thank you for spotting this 🤦

Fixed in version `3.3.6`
