### ISSUE TITLE
spiralEnabled is on even when set to false

### ISSUE THREAD

**Issue by Infinitism** [venits/react-native-map-clustering#165]
The mapview displays a spiral even when it is explicitly set to false in version 3.3.7

**Comment by venits** [comment]
Hi @Infinitism 

Did you try something like this?
```js
  <MapView
      spiralEnabled={false}
```

**Comment by Infinitism** [comment]
Yeah, I did that and it still does that.

**Comment by yl-flyer** [comment]
Same here

**Comment by venits** [comment]
Fixed in module version `3.4.0`
