### ISSUE TITLE
[Android] Clustering Markers not shown

### ISSUE THREAD

**Issue by 3plusalpha** [venits/react-native-map-clustering#166]
I tried your example code from the README file on Android and iOS and it seems that the clustering markers are not shown on Android.

IOS
<img width="584" alt="Bildschirmfoto 2020-05-18 um 00 22 29" src="https://user-images.githubusercontent.com/1685307/82161560-261e5c00-989e-11ea-8280-96732ee7da67.png">

ANDROID
<img width="517" alt="Bildschirmfoto 2020-05-18 um 00 25 22" src="https://user-images.githubusercontent.com/1685307/82161565-2ae31000-989e-11ea-95f9-9f7a14a75af1.png">

**Comment by 3plusalpha** [comment]
It might be related to `zIndex`, which was introduced just recently:

Androids `elevation` property might fix it `elevation: 1`
https://github.com/venits/react-native-map-clustering/blame/master/lib/ClusteredMarker.js#L82

Possible fix `elevation: 2`
https://github.com/venits/react-native-map-clustering/blame/master/lib/ClusteredMarker.js#L86

**Comment by Infinitism** [comment]
Sometimes setting the maxZoom to the right value will fix this for you. Play around with the right number for your app.

**Comment by 3plusalpha** [comment]
update:
react-native-maps@0.26.1: working
react-native-maps@0.27.0: not working
react-native-maps@0.27.1: working

I guess I can close this issue

**Comment by Ashkan-Oliaie** [comment]
They are not showing up for me on android ,

**Comment by Ashkan-Oliaie** [comment]
Fixed .The thing is I had my markers on another React stateless components , when I moved them directly into the mapView they are ok now.

> They are not showing up for me on android ,

**Comment by systemallica** [comment]
> 
> 
> Fixed .The thing is I had my markers on another React stateless components , when I moved them directly into the mapView they are ok now.
> 
 I had the same problem. Shouldn't it be possible to cluster Markers even if they are in another component?

Or in any case at least add a warning in the documentation.

**Comment by dragma** [comment]
Does not wor for me, neither for `0.26.1` & `0.27.1` react-native-maps versions.
Cluster markers are not shown at all on (android), even with the provided exemple.

Version of react-native : 0.61.5
