### ISSUE TITLE
initial region not being applied in the mapview

### ISSUE THREAD

**Issue by Infinitism** [venits/react-native-map-clustering#167]
I set the initial region to be the following which is just a zoom out of the entire U.S. map and this never gets applied when I set it with the `initialRegion` prop with MapView.

`
region: {
  latitude: 36.205,
  longitude: -92.756,
  latitudeDelta: 70,
  longitudeDelta: 70
}
`

**Comment by venits** [comment]
Fixed in module version `3.4.0`
