### ISSUE TITLE
Does the default maxZoom value limit what the delta can be in initiaregion?

### ISSUE THREAD

**Issue by Infinitism** [venits/react-native-map-clustering#168]
https://github.com/venits/react-native-map-clustering/blob/f1d61a7fb5434ab446806b5cefa0d47d0a197d99/lib/ClusteredMapView.js#L241

**Comment by venits** [comment]
It stands for: _Maximum zoom level at which clusters are generated._

Here is some more documentation on that:
https://github.com/mapbox/supercluster#options
