### ISSUE TITLE
LayoutAnimation bleeding outside of mapview

### ISSUE THREAD

**Issue by pdugan20** [venits/react-native-map-clustering#170]
Unless I pass animationEnabled={false} into the MapView, the LayoutAnimation you're using ends up animating a FlatList in another tab of my app. 

Any idea how I can prevent this from happening without just disabling the animation?

![animation5](https://user-images.githubusercontent.com/1837100/82773896-2b2c5f80-9df8-11ea-9d09-613ecc21d91e.gif)

**Comment by dungtran-groove** [comment]
I'm having this issue when using react-native-map-clustering and react-navigation together. By `enableScreens()` of react-native-screens the issue is gone. Need more investigation

**Comment by jbromberg** [comment]
I am also having this issue and it essentially makes this entire library useless. Any fixes?
