### ISSUE TITLE
Clustering issues with clusters at same coordinates

### ISSUE THREAD

**Issue by Adam-Schlichtmann** [venits/react-native-map-clustering#177]
Working Snack using expo 36 and: 
` "react-native-map-clustering": "^3.3.9",
    "react-native-maps": "^0.27.1"`

[SNACK](https://snack.expo.io/@mada1113/belligerent-bubblegum)

Expected: When zooming in on a cluster the correct markers show up for each respective cluster. 

Actual: Only the most recent cluster is being rendered under both clusters when zoomed in.

Steps to reproduce: 
1. Open snack on Apple or Android device
2. Click on the cluster with 4 markers in it. (You will be zoomed into the cluster)
3. Click any of the markers in the cluster. (Clicking the first one makes this more obvious)
4. Zoom out until you see the other cluster with 2 markers in it. (It is NorthWest of the cluster with 4)
5. Do NOT click on the cluster with 2. Instead, zoom in on the cluster until the markers appear. You will see the first two markers for the previous cluster of 4. If you click on one of them, you will be animated back to the cluster of 4 on the map.  
6. You can do the reverse of this by clicking the cluster with 2 then moving to the cluster with 4 and the results will be the same just reversed to always show the cluster with 2.

Let me know if you want any more examples or anything!

**Comment by CompRider** [comment]
Same issue with me, any update?

**Comment by Adam-Schlichtmann** [comment]
If there is any more context I can give please let me know

**Comment by irenmax** [comment]
I am facing the same Issue. Is there any solution for this?

**Comment by venits** [comment]
Fixed in version `3.4.0`
