### ISSUE TITLE
Please add minPoints setting of supercluster

### ISSUE THREAD

**Issue by kub1x** [venits/react-native-map-clustering#178]
Supercluster allows to set min # of points to form a cluster. Having that prop, I'd use it ;) 

https://github.com/mapbox/supercluster#options

Thanks for amazing component btw. I'm showing 1000+ markers and this lib helped to increased the performance.

**Comment by abhatia-lix** [comment]
+1

**Comment by venits** [comment]
Added in version `3.4.0`

**Comment by nguyenduy2392** [comment]
minPoints={1} android has bug can't not see maker when zoom max
