### ISSUE TITLE
Can we use this on expo production build?

### ISSUE THREAD

**Issue by DhineshKSD** [venits/react-native-map-clustering#182]
Hi, 
    Will this plugins supports for expo production builds?

**Comment by wdospinal** [comment]
Yes, I have it tested in iOS and Android work on version `3.3.9`

**Comment by AnasAlamin** [comment]
it does work but i have a blank map on standalone, can any one help?

**Comment by DhineshKSD** [comment]
For standalone builds, you have to reference google key in case you want to show google maps on both (iOS/Android). Whereas on iOS by default in expo prod builts apple maps will be loaded and not need to reference any keys.

Hope it helps.

**Comment by DhineshKSD** [comment]
> Yes, I have it tested in iOS and Android work on version `3.3.9`

Yeah worked for me too. Thanks

**Comment by AnasAlamin** [comment]
i have added Google Maps API keys for both ios and android (i'm using google maps for both), but i'm still getting a blank map
is it possible that i have wrong configs for the key?
if so, can you provide me with a guideline?

**Comment by AnasAlamin** [comment]
> For standalone builds, you have to reference google key in case you want to show google maps on both (iOS/Android). Whereas on iOS by default in expo prod builts apple maps will be loaded and not need to reference any keys.
> 
> Hope it helps.

i have added Google Maps API keys for both ios and android (i'm using google maps for both), but i'm still getting a blank map
is it possible that i have wrong configs for the key?
if so, can you provide me with a guideline?

**Comment by AnasAlamin** [comment]
just worked for me, thank you anyway
