### ISSUE TITLE
Package does not cluster markers

### ISSUE THREAD

**Issue by lucianoacsilva** [venits/react-native-map-clustering#186]
Hello,

Tried to use here the package to cluster custom markers, but they are displayed separatedly as if I were using **react-native-maps**.
It is important to mention I also insert an image inside the marker.

Regards

Luciano

**Comment by kaylakantola** [comment]
Can you provide some code samples?

**Comment by calz10** [comment]
on my side too. i followed the docs yet its like normal rn-maps and not clustering.

**Comment by adamrosey** [comment]
What's strange y'all is that I've got a mac mini building to an iphone 11 on 13.7 which succeeds in clustering, but on an iphone 11 pro max on ios 14 I get no clusters

<img width="413" alt="Screen Shot 2020-10-06 at 4 55 10 PM" src="https://user-images.githubusercontent.com/4750870/95259163-c432a480-07f4-11eb-8c2e-a1b58e1659c5.png">
![image](https://user-images.githubusercontent.com/4750870/95259223-dd3b5580-07f4-11eb-8e8c-cc73596823df.png)

**Comment by calz10** [comment]
it works when we wont make separate component and imported marker lol.

**Comment by gsevla** [comment]
Exact same problem here @calz10.

I need marker to be a separated component, but It's not working.

**Comment by JorenVos** [comment]
It's **not related** with having the Marker in a seperate component, you need to provide the `coordinate` property on the wrapper component as well. When providing `coordinate` on the parent and passing it as a prop to the nested `Marker`, clustering marker does work.

**Comment by SirPhemmiey** [comment]
I'm still having this same problem, any help please?

**Comment by ramisalem** [comment]
Why this issue is closed?

**Comment by Tchaikovsky1114** [comment]
> It's **not related** with having the Marker in a seperate component, you need to provide the `coordinate` property on the wrapper component as well. When providing `coordinate` on the parent and passing it as a prop to the nested `Marker`, clustering marker does work.

when i did find coordinate out in array item cluster doesn't works but pass coordinate props to child, it works
that is very helpful useful greatful.. you genius..... thank you so the top very much
