### ISSUE TITLE
How to animate to region within a class?

### ISSUE THREAD

**Issue by GMoon777** [venits/react-native-map-clustering#198]
map view worked fine for me but using this I cannot animate camera using the normal method and I can't use hooks in my class like useRef, is there another way? 

`  zoomToTourLocation = () => {
    this._tourZoomInterval = setInterval(() => {
      if (this.state.zoom != this.props.tourZoom) {
         console.log(this.props.tourZoom);
        this.mapView.animateCamera(
          {
            center: this.props.tourZoom,
            pitch: 0,
            duration: 750,
          },
        );
        this.setState({
          zoom: this.props.tourZoom
        });
      }

    }, 1000);
  };

  render() {

    return (

      <View style={styles.mapStyle}>
   

        <MapView
          provider={"google"}
          mapType={this.props.mapType}
          showsUserLocation={true}
          style={styles.mapStyle}
          // region={this.state.mapRegion}
          ref={ref => (this.mapView = ref)}
          zoomEnabled={true}
          initialRegion={this.props.initialMapLocation}
          clusterColor={'#BD433C'}>
        

`

**Comment by DorianNaaji** [comment]
I also can't find a way to navigate within a class component and yeah, the use of hooks is not possible.

**Comment by kimkong88** [comment]
use mapRef instead of ref. look at type definition:

    mapRef?: (ref: React.Ref<Map>) => void;
