### ISSUE TITLE
Callout out is not working

### ISSUE THREAD

**Issue by dsc-cloyd** [venits/react-native-map-clustering#2]
Callout out is not showing.

**Comment by venits** [comment]
Hi, it is working fine. All you have to do is to add those two props to your marker :)
```javascript
description={'test description'}
  title={'test title'}
```
So for example:
```javascript
 <Marker coordinate={{latitude: 52.0, longitude: 18.2}}
                    description={'test1'}
                    title={'test2'}/>
```

**Comment by dsc-cloyd** [comment]
Sorry, I forgot to tell that I am using custom callout.

` <MapView.Marker key={location.id} coordinate={{latitude: location.latitude, longitude: location.longitude}} image={Images[marker]} listings={this.props.data}>
        <StoreLocatorCallout isResult={this.props.isResult} location={location} /></MapView.Marker>`

**Comment by venits** [comment]
Hmm try to use MapView from 'react-native-maps'. If it stil won't work try to search for this issue on their repository. Here is my solution for custom callout. It works fine for me:
```javascript
import {Marker, Callout} from 'react-native-maps';

<Marker coordinate={{latitude: 52.0, longitude: 18.2}}>
                <Callout>
                    <View>
                        <Text>
                            test
                        </Text>
                    </View>
                </Callout>
            </Marker>
```

Remember to import {Marker, Callout} from 'react-native-maps'.

Let me know if you will manage to fix this problem ;)

**Comment by venits** [comment]
Also try this:
```javascript
<Callout>
    <StoreLocatorCallout isResult={this.props.isResult} location={location} />
 </Callout>
```
It look like you must put StoreLocatorCallout inside Callout.
