### ISSUE TITLE
Zoom to the next clustering split?

### ISSUE THREAD

**Issue by Werbelow** [venits/react-native-map-clustering#21]
Right now I am using the onClusterPress and the animate function to zoom in on press, however, sometimes I have to tap a couple times in order to get to the next place where the clusters 'break apart'. 

I was wondering if it's possible to zoom into the next cluster break?  

It looks like if I could get an array back from the markers that are in the cluster, I could pass that to react-native-maps fitToSuppliedMarkers method perhaps? 

I have tried playing around with the amount of zoom, and that got me closer to what I'm wanting, but not quite. 

Thanks in advance!

**Comment by venits** [comment]
Hi, I added new feature in version 1.2.4. Now onCluterPress is also returning info about markers.
Here is how it works:
```javascript
<MapView
  onClusterPress = {(coordinates,markers)=>{
   console.warn(JSON.stringify(markers))
 }}
...
</MapView>
```

You get a lot of info about markers, so I guess it should be enough to come up with some algorithm.

Please test it and tell me if it is enough :)

**Comment by DanGDroid** [comment]
it throws an error:

Converting circular structure to JSON
Object.onClusterPress

**Comment by matan335** [comment]
Where is version 1.2.4?
