### ISSUE TITLE
App is crashing on standalone

### ISSUE THREAD

**Issue by AnasAlamin** [venits/react-native-map-clustering#215]
i'm using PROVIDER_GOOGLE  from 'react-native-maps' for both ios and android, and everything is ok in dev and production mode on expo CLI, but it crashes in the standalone after installing it on phone

**Comment by AnasAlamin** [comment]
i added google maps API key and it worked but i'm now having a blank map on standalone also !!

**Comment by DariusPirvulescu** [comment]
any updates on this? Where did you add the API key?
