### ISSUE TITLE
Once zoomed into a single marker, custom marker is rendering a whole map for each point

### ISSUE THREAD

**Issue by Werbelow** [venits/react-native-map-clustering#22]
I recently updated to get the makers array back in the onClusterPress event, which is helpful :) 

However, now I am experiencing an issue where each custom marker, once no longer in a cluster, is rendering a whole new map. 

Looks like the once it's no longer in a cluster, it's getting passed a type of `MapView()` instead of `Feature` and it's getting an `item` prop, whereas the cluster markers are not. 

Seems like the change happens somewhere between v1.2.1 and v1.2.4. After going back down to 1.2.1 the custom markers render as expected. 

<img width="951" alt="screen shot 2017-11-02 at 10 32 26 am" src="https://user-images.githubusercontent.com/5963934/32338221-c006bb34-bfb9-11e7-85e8-13fd8bb94479.png">
<img width="361" alt="screen shot 2017-11-02 at 10 32 07 am" src="https://user-images.githubusercontent.com/5963934/32338222-c01a0996-bfb9-11e7-85e1-eff72e573b26.png">

Thanks in advance :)

**Comment by venits** [comment]
Hmm it's very strange. Please send source code because I can't reproduce this bug. It works fine  for me.

**Comment by Werbelow** [comment]
Thanks for the quick response, below is how I am rendering the map and the markers. 

```
<MapView
        region={{
          latitude: 40.4,
          longitude: -105,
          latitudeDelta: 10,
          longitudeDelta: 10
        }}
        ref={ref => (mapView = ref)}
        customMapStyle={MapStyle}
        style={styles.map}
        provider={PROVIDER_GOOGLE}
        clusterColor="#0D1439"
        clusterTextColor="#ccc"
        clusterBorderColor="#ccc"
        clusterBorderWidth={2}
        cacheEnabled={false}
        onClusterPress={(coordinate) => this.animate(coordinate)}
      >
        {filteredItems.map((item, i) => {
          return (
            item.lat && (
              <Marker
                coordinate={{
                  latitude: parseFloat(item.lat),
                  longitude: parseFloat(item.lng)
                }}
                key={i}
                onPress={e => {
                  e.stopPropagation();
                  this.handleMarkerPress(item);
                }}
              >
                {item.user && (
                  <View style={styles.marker}>
                    <View style={styles.markerBackground}>
                      <Image
                        source={{ uri: item.user.avatar }}
                        style={styles.avatar}
                      />
                      <Text style={styles.pointText}>{`${item.user
                        .points} PTS`}</Text>
                    </View>
                  </View>
                )}
              </Marker>
            )
          );
        })}
      </MapView>
```

**Comment by venits** [comment]
Hmm can you try same code with version 1.2.4? It seems to work for me.

**Comment by Werbelow** [comment]
Just tried again with the same code on 1.2.4, and still same issue. 

<img width="353" alt="screen shot 2017-11-02 at 12 07 17 pm" src="https://user-images.githubusercontent.com/5963934/32342604-7b94da46-bfc6-11e7-9dc7-daf81c3fd9ed.png">

**Comment by venits** [comment]
Hmm by this picture you mean, that when you start your app you have one map but after some zooming and clustering new maps are added to view?

**Comment by Werbelow** [comment]
Yeah, so it starts out great, then after zooming into where the clusters break apart and only show the single custom marker, it renders a map for each marker.

**Comment by venits** [comment]
Hmm can you try again but now remove those lines:
```javascript
customMapStyle={MapStyle}
provider={PROVIDER_GOOGLE}
```

**Comment by venits** [comment]
I think that it might be something wrong with the way markers are send to module. I mean where you have: 
```javascript
filteredItems.map(...
```
Look like it returns few things:
```javascript
 return (
            item.lat && (
              <Marker...>)
```
Please try to make it little simpler so only markers are returned.  You can start with something like this:
```javascript
 filteredItems.map((item, i) => {
            return(
                <Marker
                    coordinate={{
                        latitude: item.lat,
                        longitude: item.lng
                    }} key={i}>
                </Marker>
            );
        });
```
I am not sure if it will help but we must try :)

**Comment by Werbelow** [comment]
I just tried the very simple version, it didn't break down into maps, but it also didn't show anything at all, like no markers or anything, once zoomed in. 

The `item.lat &&` is just checking that the item has a lat, if not, it doesn't render

**Comment by venits** [comment]
Hmm ok so now try to reduce marker complexity. I mean try normal marker without other views inside and if it will work try to add custom view inside, and so on.

**Comment by Werbelow** [comment]
Ok, so I got it figured it. I was curious on why the simple marker code didn't even show the generic red marker pin image, so I switched from this:
`import Maker from 'react-native-maps'`
to 
`import { Marker } from 'react-native-maps'` 
and that seemed to clear things up. 

Thanks so much for the quick replies!
