### ISSUE TITLE
MapView should not require a region if initialRegion is set

### ISSUE THREAD

**Issue by hoboman313** [venits/react-native-map-clustering#23]
Currently react-native-map-clustering MapView crashes if the region is not set, but the initialRegion is. This is contrary to how the base react-native-map MapView behaves and causes annoying bugs (ex. map skips back to the previous region after the user moves the map) in the case that the dev wants to save the region via onRegionChangeComplete() in the redux store.

**Comment by venits** [comment]
Hi, thanks for pointing that out :)

Please check version 1.2.5, everything should work there.
