### ISSUE TITLE
Prop to exclude some markers

### ISSUE THREAD

**Issue by zorobabel** [venits/react-native-map-clustering#24]
First, kudos for this great lib. I don't have so much time to dig into the source code but want to know is there is a way to exclude some markers from clustering. Thanks in advance.

**Comment by venits** [comment]
Hi, 

I added option to exclude marker from being clustered in version 1.2.6. All you have to do is to add 'cluster' prop to marker like this:

```javascript
 <Marker
     cluster = {false}
     coordinate={{latitude: x, longitude: y}}>
 </Marker>
```

**Comment by zorobabel** [comment]
Thank you so much, Tomasz!

**Comment by Peretz30** [comment]
I am little confused here, because it didn't work for me and I can't see any prop check in source code. So I added this prop check in my fork. PR is coming.

**Comment by Showyilu** [comment]
> 

https://github.com/venits/react-native-map-clustering/blob/master/lib/helpers.js#L10

Just add cluster={false}

**Comment by webstermobile** [comment]
perfect
