### ISSUE TITLE
`mapRef` typing is not accurate

### ISSUE THREAD

**Issue by lucksp** [venits/react-native-map-clustering#245]
I think the `mapRef` definition is incorrect.  It should be assignable to a ref like so:

```
const mapRef = useRef<MapView | null>(null);  // equates to type: MutableRefObject<MapView | null>;

useEffect(() => {
    if (isMapReady) {
        mapRef?.current?.fitToElements();   
    }
  }, [isMapReady, mapRef]);

<MapView
      mapRef={(ref) => {
        mapRef.current = ref
      }}
      {...rest}
    >
      <Markers  />
    </MapView>
```

However, the `mapRef` from this library shows type of: `mapRef?: (ref: React.Ref<Map>) => void;` which results in an error:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/15162169/191580647-784b3103-65df-42a5-8fa9-e6c2762736d5.png">

Why does it think your `ref` is `(instance: MapView | null) => void`??  If i try to "see" the `ref` such as `ref.fitToElements`, it doesn't think it exists, but if I log your `ref`, it is definitely there:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/15162169/191581102-5a6d304c-269c-4982-94f1-1b0e9d00f913.png">

My work around so this compiles is to cast my local `mapRef` as `any`
Thoughts on this?

**Comment by lucksp** [comment]
this works:

```
interface ProviderProps {
  mapRef: MutableRefObject<MapView | null>;
}

const ClusterMapProvider = () => {
  const mapRef = useRef<MapView>(null);

return <ClusterMapContext.Provider>{children}</ClusterMapContext.Provider>;
}

const Component = () => {
  const { mapRef  } = useClusterMapContext();

return (
    <MapView
      ref={mapRef}
      {...rest}
    >
      {markers && clusters}
    </MapView>
  );
}
```

**Comment by PineAppleGrits** [comment]
? Am i wondering where's "ClusterMapContext" now. I think this may be outdated, but the ref stills being inaccurate
