### ISSUE TITLE
react-native-map-clustering can not cluster with child component

### ISSUE THREAD

**Issue by zhenguet** [venits/react-native-map-clustering#248]
I'm using [react-native-maps][1] and [react-native-map-clustering][2].

I try to customize animated marker.

But I put the marker into an other component, map does not cluster.

E.g:

    import MapView from 'react-native-map-clustering';
    import {AnimatedRegion, Marker} from 'react-native-maps';

> Do not use component

```javascript
    <MapView initialRegion={INITIAL_REGION} style={{flex: 1}}>
      {localData?.map((marker: any) => {
        // return <Vehicle key={marker.CarID} marker={marker} />;

        return (
          <Marker.Animated
            key={marker.CarID}
            coordinate={{
              latitude: marker.Lt,
              longitude: marker.Ln,
              latitudeDelta: LATITUDE_DELTA,
              longitudeDelta: LONGITUDE_DELTA,
            }}
            anchor={{x: 0.5, y: 0.5}}
            tracksViewChanges={false}>
            <Animated.View style={styles.markerWrap}>
              <Animated.Image source={Car} style={styles.marker} />
            </Animated.View>
          </Marker.Animated>
        );
      })}
    </MapView>
```
[![enter image description here][3]][3]

> Use component

```javascript
    <MapView initialRegion={INITIAL_REGION} style={{flex: 1}}>
      {localData?.map((marker: any) => {
        return <Vehicle key={marker.CarID} marker={marker} />;

        return (
          <Marker.Animated
            key={marker.CarID}
            coordinate={{
              latitude: marker.Lt,
              longitude: marker.Ln,
              latitudeDelta: LATITUDE_DELTA,
              longitudeDelta: LONGITUDE_DELTA,
            }}
            anchor={{x: 0.5, y: 0.5}}
            tracksViewChanges={false}>
            <Animated.View style={styles.markerWrap}>
              <Animated.Image source={Car} style={styles.marker} />
            </Animated.View>
          </Marker.Animated>
        );
      })}
    </MapView>
```
[![enter image description here][4]][4]

  [1]: https://github.com/react-native-maps/react-native-maps
  [2]: https://github.com/venits/react-native-map-clustering
  [3]: https://i.stack.imgur.com/FsbsK.png
  [4]: https://i.stack.imgur.com/u3Jc6.png

**Comment by Bogdan2904** [comment]
try adding the coordinate field as a props for your component
<img width="480" alt="Screenshot 2022-12-17 at 16 49 33" src="https://user-images.githubusercontent.com/34319167/208247664-0e2ae0a7-49fc-4cf5-afd9-a91b0fc0b9dc.png">

**Comment by zhenguet** [comment]
@Bogdan2904 OH yes. I got it, I forget update here. as you say, children component have to have coordinate.

tks you.
