### ISSUE TITLE
Minimum distance setting to avoid overlapping clusters

### ISSUE THREAD

**Issue by strindhaug** [venits/react-native-map-clustering#25]
Not sure if this is a missing setting, bug or just an undocumented setting.
It seems to me that the clusters some times are created too close together so that they overlap:

![overlapping_clusters](https://user-images.githubusercontent.com/2144849/32788583-e9c71d52-c959-11e7-8730-871ca14f38a7.png)

Perhaps the current minimum distance before markers are grouped is too small, at least when there's as many as in my sample data. Several clusters are overlapping so bad you cannot tell which number is on them; and onClusterPress becomes very unreliable since you cannot tell which one you're tapping.

To me it seems most logical to never create clusters that are within the radius of a neighbouring cluster.

Is this configurable somewhere or is this simply a bug?

**Comment by venits** [comment]
Hi, 
it's not a bug for sure :) It is just a matter of 'radius' parameter.

**Please check version 1.2.7**, I added prop called 'radius' which you can send to control clustering behaviour. Here is an example:
```javascript
 <MapView
     style={{width: width, height: height}}
     radius = {30}
     initialRegion = {this.state.region}>
       {this.state.markers}
 </MapView>
```

Default value of radius is 17. You have to just play with this parameter to find your perfect value ;)
