### ISSUE TITLE
custom cluster marker text size.

### ISSUE THREAD

**Issue by waghih** [venits/react-native-map-clustering#27]
Hi, is there any way to have custom text size for cluster marker. Because the text seems overflow if it doesn't fit the size of custom cluster marker. Appreciate if you can help. Thank you.

**Comment by venits** [comment]
Hi, please check version 1.2.8.
I added **clusterTextSize** prop that you can add to MapView. Now you can control your cluster text size :)
```javascript
  <MapView
     clusterTextSize = {40}      
     ... >
     {this.state.markers}
  </MapView>
 ```

**Comment by waghih** [comment]
Hi, appreciated with the helps. But seems that your solution is not working.

**Comment by venits** [comment]
Make sure you are using version 1.2.8.
If not use this command:
**npm update react-native-map-clustering**

**Comment by waghih** [comment]
Cool. Thank you (y). Is there any way to access supercluster method like getClusters(). I would like to get markers on current region.

**Comment by venits** [comment]
Hmm, yes it is possible but is rather hard because you need to calculate zoom level. If you provide wrong wrong zoom level you will get empty array most of the time. You can try to play with it, here is example code:
```javascript
onClusterPress = {(cor,markers)=>{
  var markers = this.map.superCluster.getClusters([bbox[0], bbox[1], bbox[2], bbox[3]], zoom);
  console.warn(JSON.stringify(markers))
}}
```
 
Bbox is array array of [East, South, West, North] coordinates.

**Comment by waghih** [comment]
Hmmm, i only trying to get (count) visible markers on region.
