### ISSUE TITLE
Clustering , Custom Markers Not displaying on Android 

### ISSUE THREAD

**Issue by Jagadish-gif** [venits/react-native-map-clustering#278]
Here is the video How it behaves 

https://github.com/user-attachments/assets/e595b273-e8eb-4da7-8b49-8561956affc3

Getting the data in a formate of JSON 

const toggleClustering = useCallback(() => {
    setClusteringStatus(prev => !prev);
  }, []);

useEffect(() => {
    fetchMarkers();
    const intervalId = setInterval(() => {
      fetchMarkers();
    }, 60000); // 60000 ms = 1 minute
    return () => clearInterval(intervalId);
  }, [fetchMarkers]);

  useEffect (()=>{
    filterMarkers();
  }, [allMarkers, selectedCategory, selectedStatus]

<MapView 
        ref={mapRef}
        style={{ flex: 1 }}
        clusteringEnabled = {enableCluster}
        initialRegion={{ // Use userLocation if available
          latitude: userLocation ? userLocation.latitude : 12.983727,
          longitude: userLocation ? userLocation.longitude:  77.504738,
          latitudeDelta: 0.1,
          longitudeDelta: 0.1,
        }}>
        {filteredMarkers.map((marker, index) => (     
            <Marker
              key ={`${index}`}
              coordinate={{ latitude: marker.latitude, longitude: marker.longitude }}
              tracksViewChanges={false}
              onPress={() => { handleMarkerPress(marker)}}
            >
              {<View style={[styles.customMarker, { backgroundColor: getMarkerColor(marker.currentstatus) }]}>
                <Text style={styles.markerLabel}>
                  {getMarkerLabel(marker.category)}
                </Text>
              </View>}
            </Marker>
          ))}
          

          {userLocation && (
              <Marker coordinate={userLocation}>
                <View style={styles.userLocationMarker}>
                  <View style={styles.innerCircle} />
                </View>
              </Marker>
          )}
      </MapView>

Packages Using 

"@react-native-community/geolocation": "^3.3.0"
"expo-location": "^18.0.2",,
 "react-native-map-clustering": "^3.4.2",
 "react-native-maps": "^1.18.0",
    "@types/react": "^18.3.12",
    "@types/react-native-maps": "^0.24.2",

**Comment by cloud27** [comment]
Hi, same here. It works on iOS but I have the same issue on Android. Did you find out why ?

**Comment by AdamKundracik** [comment]
Solution? Seeing this closed for some reason without result
