### ISSUE TITLE
No onRegionChange callback

### ISSUE THREAD

**Issue by WalasPrime** [venits/react-native-map-clustering#28]
The original MapView from `react-native-maps` provides an `onRegionChange` callback, which can be used in the following case:

```
<MapView region={this.state.region} onRegionChange={(region) => this.setState({ region })} />
```

Without the callback the map is basically locked in place in this case.
Or is there a way to perhaps access the _original_ MapView object?

**Comment by venits** [comment]
Hi,
yes you can access original MapView object in 2 steps:
1. Create reference in your main MapView:
```javascript
<MapView
    ref = {(ref)=>this.mapView=ref}
     ...
</MapView>
```
2. Acces original MapView:
```javascript
let originalMapView = this.mapView._root;
```
That's all. 
**Tell me if that solves your problem :)**

**Comment by WalasPrime** [comment]
Actually the example I've provided works just fine if you don't modify the initial region.
`<MapView region={someInitialRegion} onRegionChange={(region) => this.setState({ region })} />`
I thought `onRegionChange` isn't called at all, but it is after all.
Thanks for the help!
