### ISSUE TITLE
fitToElements sometimes zooms in way too far

### ISSUE THREAD

**Issue by strindhaug** [venits/react-native-map-clustering#29]
I'm trying to have the map zoom in or out to show the different markers when filtering the markers.
Sometimes it works ok (though the cluster markers are sometimes outside the map somewhat).
But other times it seems to go crazy and zoom in as far as possible at a random spot on the map somewhere inside the area where the markers are.
It zooms in so far that a small building on the map covers the screen, and then it refuses to try zooming out again.

I assumed it could be an issue of the markers not being done being filtered yet, as it most often happened with text search filtering; so I added 5 second delay after filtering before calling fitToElements, but it doesn't help. When i change the code to use plain MapView without clustering it works fine.

I'm thinking the issue might be that the clustering is yanking markers in and out of the map while zooming causing the fitToElements to zoom even further when pseudo markers are removed until no markers are visible (and I assume those far outside the viewport are removed for performance reasons) and therefore it stops.
It seems to only happen when the filtering reduces the markers from covering the whole of Norway to just covering a city (especially one with a lot of markers).
When it's working okay, it seems tries to fit the center of the clusters that were there before zooming, instead of the actual markers, since it will zoom in and split a cluster and if I pan the map there is often other clusters or markers outside the viewport that was originally inside the cluster (seems to happen more far north than in the south of norway).

Is there some other method that is recommended when using clustering for zooming in?

**Comment by venits** [comment]
Hmm there might be few problems in that case actually.
Please send me all markers and code you use for zooming.
I will try to recreate this problem and find solution :)

**Comment by strindhaug** [comment]
I've found a workaround but I've created a gist with a stripped down an slightly anonymized version, where I have commented out the workaround and uncommented the weird code. 

The client probably don't want me to share the code with the whole world anyway;  so is there any way I can share the url with you privately somehow?

**Comment by strindhaug** [comment]
What the heck... Here it is: https://gist.github.com/strindhaug/01cae75dbdd293bc77c56d194c5377aa 
let me know as soon as you've downloaded it so I can delete it.

The data originally contains 1400 markers but I truncated it down to 300, and it seems to be enough to still trigger the bug. A search for "Oslo" once the view has loaded should trigger the bug.

**Comment by venits** [comment]
Ok done, you can delete

**Comment by strindhaug** [comment]
I'll share my workaround for others who have the same problem. (It's probably more efficient as well since it uses stored coordinates and not live markers that might change during the zoom)
This also has the benefit of allowing you to specify edge padding so that the markers is kept well within the viewport:

```js

getFilteredMarkerData = () => {
    const markers = this.state.allData.filter(
    marker =>
      marker.someValue >= this.state.minValue &&            
      marker.someOtherValue == this.state.searchValue
      // etc. etc.
  );
  // Save the current coordinates:
  this.state.coordinatelist = markers.map(marker => {
    return marker.coordinates;
  });
  return markers;
};

// A short time later (using a timeout or a throttled funtion etc):


if (this.state.coordinatelist.length > 0) {
  // In stead of "this.mapView._root.fitToElements(true);" do this:
  this.mapView._root.fitToCoordinates(this.state.coordinatelist, {
    edgePadding: {
      // tweak these if needed 
      top: 50,
      right: 50,
      bottom: 50,
      left: 50,
    },
    animated: true,
  });
}
  
```

**Comment by venits** [comment]
Hi, yep I am looking at project you send me and ye are right due to performance optimization, markers that are far away from viewport and not displayed at all. That way calling this.mapView._root.fitToElements(true); will not work.

To make fitToElements(true) work:
1. You have to move user to coordinates of the city. 
2. Call this.mapView._root.calculateClustersForMap();
3. this.mapView._root.fitToElements(true);

But I see that you found even better workaround so you should be fine :)
