### ISSUE TITLE
unable to AnimateToRegion

### ISSUE THREAD

**Issue by derrick-exabytes** [venits/react-native-map-clustering#3]
Hi Venits,

Thanks for the cool module, 
but i'm getting error "this.mapRef.animateToRegion" is not a function when i trying to programatically animate to a region.

Can you please advise? 

Thanks

**Comment by venits** [comment]
Hi Derrick,
Thanks for noticing this problem ;)

Here is solution:

**For things like animateToRegion or animateToCoordinate and other methods all you have to do is to refer to _root in your MapView reference**.

Example:
- Create reference to your main MapView.
```javascript
    <MapView
            ref = {(ref)=>mapView=ref}
            ...
    </MapView>
```
- With that reference you can for example animateToRegion like this:
```javascript
    animate(){
       let r = {
            latitude: 42.5,
            longitude: 15.2,
            latitudeDelta: 7.5,
            longitudeDelta: 7.5,
        };
        mapView._root.animateToRegion(r, 2000);
    }
```

**Comment by Nitingadhiya** [comment]
Hi Venits,
I have same issue with animateToRegion function. Means some time work and some time not working. Would you please help us. how to solve my problem.

**Comment by salimakhtar18** [comment]
Sorry this is not working for me.

function ```animate()``` is not calling

my code is:
```
        <MapView
          ref={map => {
            mapView = map;
          }}
          provider='google'
          clustering={true}
          onClusterPress={this.onPressCluster}
          region={this.state.region}
          onRegionChange={this.onRegionChange}
          onRegionChangeComplete={this.onRegionChangeComplete}
          style={styles.map}
          showsUserLocation={true}
          followUserLocation={true}
          zoomEnabled={true}
          ScrollEnabled={true}
          showsBuildings={true}
          showsMyLocationButton={false}
        >
```

**Comment by mohmdalfaha** [comment]
I really don't understand why you guys don't show a complete code or answer ??

> Hi Derrick,
> Thanks for noticing this problem ;)
> 
> Here is solution:
> 
> **For things like animateToRegion or animateToCoordinate and other methods all you have to do is to refer to _root in your MapView reference**.
> 
> Example:
> 
> * Create reference to your main MapView.
> 
> ```js
>     <MapView
>             ref = {(ref)=>mapView=ref}
>             ...
>     </MapView>
> ```
> 
> * With that reference you can for example animateToRegion like this:
> 
> ```js
>     animate(){
>        let r = {
>             latitude: 42.5,
>             longitude: 15.2,
>             latitudeDelta: 7.5,
>             longitudeDelta: 7.5,
>         };
>         mapView._root.animateToRegion(r, 2000);
>     }
> ```

**Comment by venits** [comment]
H all, I changed implementation a little bit.
Now you have to use mapRef instead of ref.

Example:

<MapView mapRef={ref => this.mapView = ref} />

In case of any problems please open issue.
