### ISSUE TITLE
won't know how many markers are merged

### ISSUE THREAD

**Issue by shenlongdemon** [venits/react-native-map-clustering#32]
When some markers are merged, we don't know how many
So, i suggest when some markers are merged, we should do as onClusterPress do (#3)
such as

customClusterMarkerDesign = ((coordinates,markers)=>{
          (<Image style = {{width: imageWidth, height:imageHeight}}
        source = {require('./customCluster.png')}/>)}}

ex: when 10 markers are merged, we based on type of them and show 10 and background of marker, we split 2 parts with red area is 30% and green area is 70%

Thank you

**Comment by venits** [comment]
Yes you can add it to your code but I can't add this to module because this is not very common usage and most users prefer old way.

**Comment by DanGDroid** [comment]
hi,
i would like to get data about markers in cluster to display on custom cluster
