### ISSUE TITLE
sometimes after load map markers is not showing

### ISSUE THREAD

**Issue by dennisbejencev-an** [venits/react-native-map-clustering#38]
example:
map on load https://prnt.sc/hiw4oo
map after some zoom https://prnt.sc/hiw4u8

**Comment by venits** [comment]
It is bug in [react-native-map-view](https://github.com/airbnb/react-native-maps). 
You have to look that up in issues.

**Comment by dennisbejencev-an** [comment]
I not sure, because before using your library markers was showing correct

**Comment by dennisbejencev-an** [comment]
can be something with http://prntscr.com/hk76uo

**Comment by dennisbejencev-an** [comment]
the problem in the code http://prntscr.com/hk7qe6
