### ISSUE TITLE
when maximum zoom markers is not showing

### ISSUE THREAD

**Issue by dennisbejencev-an** [venits/react-native-map-clustering#39]
example:
map on load https://prnt.sc/hiw4oo
map after some zoom https://prnt.sc/hiw4u8
I not sure that It is bug in react-native-map-view, because before using your library markers was showing correct.
when I turn off clustering, markers are showing always
the problem in the code http://prntscr.com/hk7qe6

**Comment by venits** [comment]
Hmm ok I will check it. Can you give me your code where you implement MapView and also all markers you are using?

**Comment by dennisbejencev-an** [comment]
yes, pls check
https://pastebin.com/YAyXGc05

**Comment by venits** [comment]
Hmm I will try to solve this issue when I will have some free time this weekend. 
For now please check if it works with markers without images. I think there might be something wrong with that.

**Comment by dennisbejencev-an** [comment]
hello, do you have a think where exactly is the bug?

**Comment by venits** [comment]
Hi, I found bug that is related with supercluster library my module is using.
To problem is that init region latitudeDelta and longitudeDelta must be less that 70. 
So for example 68.
I am not sure If I can fix that but it should not be a big problem for your app.
Just do:
```javascript
 latitudeDelta: 68,
 longitudeDelta: 68,
```
and your app should work as expected.
Please let me know if that solved your problem ;)

**Comment by dennisbejencev-an** [comment]
it fixes only for initial render, if after initial render make minimal zoom markers is hiding again, and I noticed that border of delta for different markers is different it from 70 to 100

**Comment by venits** [comment]
Hmm it all about the zoom I think and the problem lies in algorithm.
I will try to overcome this in my free time :)

**Comment by dennisbejencev-an** [comment]
thanks, I hope you will succeed)

**Comment by dennisbejencev-an** [comment]
what about the issue? Could you fix it?
