### ISSUE TITLE
Cluster Double Click

### ISSUE THREAD

**Issue by FrK492** [venits/react-native-map-clustering#44]
When i double click a cluster it opens one of the markers inside the cluster on iOS. How can i solve that issue? i tried to pass a function to onClusterPress but its not working.

**Comment by venits** [comment]
Hi, what you mean by 'opens one of the markers '?
It is like onPress is called or it zooms to this marker?

Also, can you share your code? Maybe I will be able to help you :)

**Comment by FrK492** [comment]
When i click it once onClusterPress called but pressing twice triggering onPress function of one of the marker's callout which inside of that cluster. 
`<Marker
									key={i}
									coordinate={this._parseCoordinates(place.Coordinate)}
									onCalloutPress={() => this.props.navigation.navigate('Place', { place: place })}>
									<Callout tooltip>
										<View style={{ backgroundColor: '#08b4bc', borderRadius: 20, padding: 10 }}>
											<Text style={{ color: '#fff' }}>{place.Title}</Text>
										</View>
									</Callout>
								</Marker>
							))`

**Comment by venits** [comment]
Hmm works fine for me :I 
Pressing twice only zoom to clicked cluster for me. 
Also it is onCalloutPress so callout must be show first of all.

**Comment by dennisbejencev-an** [comment]
@FrK492 sorry me, but can you check the issue https://github.com/venits/react-native-map-clustering/issues/38, do you have the same problem or no?
