### ISSUE TITLE
Can't see the group of markers onClusterPress

### ISSUE THREAD

**Issue by ewein** [venits/react-native-map-clustering#45]
I'm trying to get the group of markers as an object when I press a cluster however right now when I try to `JSON.stringify` the markers data (same as in the docs) it errors out because of cyclic structures (`json.stringify cannot serialize cyclic structures`). Is it possible to get the markers back as just an object? Thanks!

```
                <MapView
                    ref={component => {this._map = component;}}
                    clustering={true}
                    showsUserLocation={true}
                    showsMyLocationButton={false}
                    initialRegion={this.state.region}
                    onRegionChange={this._onRegionChange}
                    onClusterPress={(coordinates, markers) => {
                           console.warn(JSON.stringify(markers))
                    }}
                    style={styles.mapView}
                >
```

**Comment by hunght** [comment]
@venitsI have the same thought about how to get all markers of the cluster.pls, help me.

**Comment by salimakhtar92** [comment]
@venits  I am facing the same issue that how to get all markers in side a cluster when I clicked on cluster:
```
onClusterPress = {coordinates => console.log(coordinates)}
```
When I am clicking on cluster icon I am getting an event.

Please tell me how to fix this issue.

**Comment by venits** [comment]
Hi all,

I released new version of this library.

In new version **onClusterPress()** works like this:

```js
const onClusterPress = (cluster, markers) => {
  console.warn(cluster, markers);
};
```

Let me know if that works for you ;)
