### ISSUE TITLE
When max zoomed out on map the clusters disappear

### ISSUE THREAD

**Issue by ewein** [venits/react-native-map-clustering#46]
Maybe need to increase the max marker amount for the clusters. It looks like there are too many points to cluster so its hiding the cluster maybe?

**Comment by dennisbejencev-an** [comment]
only clusters or also markers? I have similar problem
https://github.com/venits/react-native-map-clustering/issues/39

**Comment by ewein** [comment]
Seems to be only clusters.

**Comment by ewein** [comment]
Seems to be only clusters.

**Comment by boubrives** [comment]
same issue goes with or without image in marker (answering about suggestion in issue #39 )

**Comment by venits** [comment]
I released new version of this library. This issue should is solved 🎉

**Comment by abdullah2011-gif** [comment]
Each marker need to have a unique key prop. In my case this was causing markers to disappear on random zoom levels.
<Marker key={key}
   coordinate={{...marker}}>
