### ISSUE TITLE
Undefined is not an object (evaluating 'item.props.cluster')

### ISSUE THREAD

**Issue by xaurav91** [venits/react-native-map-clustering#49]
This code was working with react-native-maps MapView. It shows an error with this package. 
` <MapView`
`               initialRegion={this.state}`
`                clusterColor = '#000'`
`                clusterTextColor = '#fff'`
`                clusterBorderColor = '#fff'`
`                clusterBorderWidth = {4}`
`                ref = {(ref)=>this.mapView=ref}`
`                onClusterPress={(coordinate)=>{`
`                    this.animate(coordinate);`
`                }}`
`                radius={25}`
`                style={styles.map}`
`                region={region}`
`                showsUserLocation = {true}`
`                 >`
`               {  this.renderMarker(selectedExplore)}`
`                        <WardBorder/>`
`                </MapView>`

And on WardBorder component

` <Polygon `
`                    coordinates={cords}`
`                    strokeColor="rgba(0,0,0,0.2)"`
`                    fillColor="rgba(0,0,0,0.1)"`
`                    strokeWidth={1} />`

But if i comment out the WardBorder (polygon) component marker is clustered.

**Comment by sujalbinno** [comment]
Make following changes in react-native-map-clustering/MapView/MapWithClustering.js file 

```
       if (item.props && item.props.cluster !== undefined) {
          canBeClustered = item.props.cluster
        }
        // item.props.cluster === undefined ? canBeClustered = true : canBeClustered = item.props.cluster;
```

**Comment by venits** [comment]
I released new version of this library. This issue should be solved 🎉
