### ISSUE TITLE
onPress cluster component

### ISSUE THREAD

**Issue by sberryman** [venits/react-native-map-clustering#5]
How would you go about capturing the onPress event for the cluster component? I would like to zoom to the region of markers when pressing a cluster. It would also be nice if we could override the cluster component as well.

Custom cluster component where you pass an array of markers would let me render a price range for the clustered markers for instance.

Thanks again for the great clustering component!

**Comment by venits** [comment]
Hi, I think I can do that :) Give me one day and I will update you on my progress on that issue.

**Comment by venits** [comment]
Hi again, I added onClusterPress prop so that should solve your problem. Here is solution:
1. Define you zoom animation function:
```javascript
    animate(coordinate){
       let newRegion = {
            latitude: coordinate.latitude,
            longitude: coordinate.longitude,
            latitudeDelta: mapView.state.region.latitudeDelta - 1,
            longitudeDelta: mapView.state.region.longitudeDelta - 1,
        };
        mapView._root.animateToRegion(newRegion, 1000);
    }
```
2. Add **onClusterPress** prop to your MapView.
```javascript
    <MapView
        ref = {(ref)=>mapView=ref}
        onClusterPress={(coordinate)=>{
            this.animate(coordinate);
        }}
       ...
    </MapView>
```


And for this custom clustering  you want to only cluster markers with the same price?.  Am I right?

**Comment by sberryman** [comment]
Excellent news @venits! Thanks so much for implementing this so quickly, looking forward to trying it out today.

**Comment by sberryman** [comment]
Ideally I was looking for an array of annotations/markers passed as an argument to the onPress function. The coordinate of the clustered pin should be enough for me to zoom in though.

I was just going to take the array of annotations and pass them to `map.focusMap` as shown:
https://github.com/airbnb/react-native-maps/blob/master/example/examples/FitToSuppliedMarkers.js

**Comment by Clowning** [comment]
Hey @venits thanks for your solution but it doesn't work ! The zoom is very small at the beggining and is it more bigger if a top few times on my marker, and after few tap i've an error ! Because delta is negative! :/

**Comment by venits** [comment]
Hi, Clowning my solution is not perfect because it is just an example. Here:
```javascript
latitudeDelta: mapView.state.region.latitudeDelta - 1,
```
You have to handle this {-1} value on your own and also catch negative delta.

**Comment by silviomedice** [comment]
Hello everybody,
I had the same problem and did like this. 
    animate(coordinate){
        let newRegion = {
            latitude: coordinate.latitude,
            longitude: coordinate.longitude,
            latitudeDelta: mapView.state.region.latitudeDelta *0.1,
            longitudeDelta: mapView.state.region.longitudeDelta *0.1,
        };
        mapView._root.animateToRegion(newRegion, 1000);   
     }

**Comment by venits** [comment]
Hi @silviomedice,
in recent version of module I changed `_root` for `root`. 
I hope you will not run into problems ;)

**Comment by silviomedice** [comment]
@venits  Thanks a lot, I was having problems with IOS, but not on Android. But you saved me.
