### ISSUE TITLE
Custom cluster's text position

### ISSUE THREAD

**Issue by tamirwd** [venits/react-native-map-clustering#59]
Is it possible to set the position of the cluster's text ?

There are props to define all cluster's text attributes, and also a method to set its background, but unfortunately it's not enough in my case since I also want to show the text in a specific position relative to the custom background I'm using.

**Comment by venits** [comment]
I released new version of this library.

It will be possible to control cluster style but it will require handling cluster logic on your own.
I can implement prop called **renderCluster** and there you will be able to define cluster styles on your own.

Let me know if that issue is still relevant.

**Comment by venits** [comment]
I added new prop called **renderCluster** that allows you to control logic and style of cluster.

Upgrade module to version **"3.0.3"**.

Here is code example of how it works:

```js
const renderCluster = cluster => {
  const { id, geometry, onPress, properties } = cluster;
  const points = properties.point_count;

  return (
    <Marker
      key={`cluster-${id}`}
      coordinate={{
        longitude: geometry.coordinates[0],
        latitude: geometry.coordinates[1]
      }}
      onPress={onPress}
    >
     <View>
       <Text>{points}</Text>
     </View>
   </Marker>
  );
};

return (
  <MapView
    renderCluster={renderCluster}
  >
    // markers
  </MapView>
);
```
