### ISSUE TITLE
onClusterPress is not triggered

### ISSUE THREAD

**Issue by JonatanGC** [venits/react-native-map-clustering#6]
Hi Venits,

Thank you very much for this component.

I'm trying the onClusterPress method but is not being triggered because is undefined on the state.

Fix: I added locally onClusterPress to the default state and on the assignment made on createMarkers() but I'm not sure if that it's a good solution for you.

Thanks.

**Comment by venits** [comment]
Hi,
that's strange because it should work :)
 First please make sure that you are using version >= 1.1.4 of my module because I added it in this version.
Here is full code that works for me:

```javascript
 animate(coordinate){
        let newRegion = {
            latitude: coordinate.latitude,
            longitude: coordinate.longitude,
            latitudeDelta: mapView.state.region.latitudeDelta - mapView.state.region.latitudeDelta/2,
            longitudeDelta: mapView.state.region.longitudeDelta - mapView.state.region.longitudeDelta/2,
        };
        mapView._root.animateToRegion(newRegion, 1000);
    }

  render() {
    return (
        <MapView
            ref = {(ref)=>mapView=ref}
            onClusterPress={(coordinate)=>{
                this.animate(coordinate);
            }}
            region={this.state.region}
            style={{width: width, height: height}}>
            {this.state.markers}
        </MapView>
    );
  }
```

**Comment by JonatanGC** [comment]
Thanks for your quick response,

Now it's working and I'm unable to reproduce the issue, I was using v1.1.4.

Sorry for the inconvenience

**Comment by salimakhtar92** [comment]
Hi
I am using this package of version ``` "react-native-map-clustering": "^1.1.4" ```
And i have written following code:
```
animate(coordinates){
        console.log(coordinates)
}

render() {
    return (
        <MapView
            ref = {(ref)=>mapView=ref}
            onClusterPress={(coordinates)=>{
                this.animate(coordinates);
            }}
            ......
            ...........
        </MapView>
    );
  }
``` 
But i am getting following in log instead of coordinates : 

See the screen short

![screen shot 2018-08-10 at 3 39 44 pm](https://user-images.githubusercontent.com/42136495/43952468-a8be58ce-9cb3-11e8-8464-9171e212e557.png)
