### ISSUE TITLE
MapView ref became this.root

### ISSUE THREAD

**Issue by vhoen** [venits/react-native-map-clustering#64]
This commit https://github.com/venits/react-native-map-clustering/commit/9420a0795c67819e9ae6ca328e55b7e679a5e2a7#diff-b75bf6bb36e3beebc410d167c3ecb1e1R158 changes MapView ref from `this._root` to `this.root`.
I had to access this ref in order to use some method such as animateToRegion or fitToCoordinates.

Are we supposed to use `this.root` from now on ?

Thanks in advance.

**Comment by venits** [comment]
Yep, thank you so much for pointing that out. I totally forgot about it :)

**Comment by venits** [comment]
First you must have ref to `<MapView/>`. It will look like this:
```js
<MapView
  ref={ref => this.mapView = ref}
  onClusterPress={() => console.warn(this.mapView.root)}
>
{markers}
</MapView>
```

**Comment by uptophnarita** [comment]
@venits Thank you! This worked.
