### ISSUE TITLE
onClusterPress arguments have changed

### ISSUE THREAD

**Issue by vhoen** [venits/react-native-map-clustering#65]
It seems that what was passed to onClusterPress has recently changed.
We used to receive an object containing latitude and longitude (cf. 1st image), while we now receive an event (cf. 2nd image).

Is that an undocumented update ?

<img width="258" alt="capture d ecran 2018-03-20 a 13 57 11" src="https://user-images.githubusercontent.com/5245902/37660220-cef946d2-2c49-11e8-9981-cf48d8b562eb.png">
<img width="852" alt="capture d ecran 2018-03-20 a 14 02 11" src="https://user-images.githubusercontent.com/5245902/37660222-cf6405bc-2c49-11e8-8b5b-3b543275aa58.png">

**Comment by venits** [comment]
Ye, sorry for that. I changed structure of whole project.
I reduced whole source code by 50%. 
Before module was to complicated and had to many features.
Average user was using like 2,3 out of 10 features, but other features were there so it was bad for performance.
Right now module is reduced to basic features, but code style and structure gives more flexibility to developers.
My goal is to create module that everyone can modify to own needs.

You can still use old version of this module, but if you want some feature in new module, you have to develop them by yourself.

**Of course if you don't know how to do it, let me know I will help :)**

**Comment by pentanaveen** [comment]
How to get coordinates and markers from the event?

**Comment by venits** [comment]
Event do not contain any information about markers. You have to code them by yourself.

**Comment by uptophnarita** [comment]
@venits Which version of the module can I use to get the latitude and longitude object?

**Comment by venits** [comment]
@uptophnarita try version `1.2.6`

**Comment by uptophnarita** [comment]
@venits Thank you for the fast responses!

**Comment by DikshaDeep** [comment]
Hello @venits 

I am using version ```1.2.6``` but i am not getting ```lat and long```.

please tell me how to get the ```lat and long```?
