### ISSUE TITLE
Cluster not show if we wrap marker on custom component

### ISSUE THREAD

**Issue by dashracer** [venits/react-native-map-clustering#66]
Hi, thank you for this great library.

I've success fully implement this library and follow the example. 
The clustering was working fine.

When I tried to create a custom component for my marker.
I tried to create a `<JobMarker/>` component that wrap `Marker` and `Callout` component.

Clustering not shown on the map.

How can I solve this?

Thank Your

**Comment by venits** [comment]
Hi, ye this is basically how module works.
You can make it work simply by passing **coordinate** prop to your <JobMarker/>.

*You have to pass  **coordinate** prop to your marker too.*

Here how it may look like:
```js
<JobMarker coordinate={{ latitude: 55, longitude: 18 }}>
   <Marker coordinate={{ latitude: 55, longitude: 18 }}
/>
```
I know it not very elegant solution but it will work ;)
