### ISSUE TITLE
Expanding cluster when clicking on it

### ISSUE THREAD

**Issue by ChrisEelmaa** [venits/react-native-map-clustering#67]
hey,

I am trying to expand cluster when clicking on it. I've forked the repository and managed to get here with my onClusterPress:

```
const onClusterPress = (e: any, cluster: any) => {

if (!cluster.geometry || !this.superCluster || !this.root || !this.state.currentRegion) {
    return;
}

const coordinates = cluster.geometry.coordinates;
const curZoom = this.getBoundsZoomLevel(
    this.calculateBBox(this.state.currentRegion as any),
    {
        height: h(100),
        width: w(100),
    }
);
const clusterExpansionZoom = this.superCluster.getClusterExpansionZoom(cluster.properties.cluster_id, curZoom);

this.root.animateToRegion({
    longitude: coordinates[0],
    latitude: coordinates[1],

    latitudeDelta: this.state.currentRegion.latitudeDelta / clusterExpansionZoom,
    longitudeDelta: this.state.currentRegion.longitudeDelta / clusterExpansionZoom,
}, 100);

// TODO:
// this timeout is hack,
// need to figure out how to do this correctly without timeout,
// for some reason it does not work without.
setTimeout(() => this.calculateClustersForMap(this.state.currentRegion), 500);
};
```

for some reason, it does not work exactly like I would hoped for - it expands by random zoom. Does anyone have any recommendations how do I incorporate clusterExpansionZoom with react native maps?

**Comment by venits** [comment]
Using this.superCluster is rather bad idea. This module play by itself rules. 

The best approach will be to calculate zoom level on your own. 
For example you can get all markers in clicked cluster and maybe calculate zoom level.

I know it is a lot of work, but I think this is the most stable way.

**Comment by ChrisEelmaa** [comment]
thanks. I did like you suggested.

here is a method which gives you longitude/latitude/longitudeDelta/latitudeDelta if you pass in all the points of a cluster:

https://stackoverflow.com/questions/32557474/how-to-calculate-delta-latitude-and-longitude-for-mapview-component-in-react-nat

all you need to do is just call animateToRegion() and voila! I will add one gotcha; you need to use map/reduce functions of superCluster in order to "aggregate" all the coordinates that the cluster holds, otherwise you have no access to it.


```
this.superCluster = new SuperCluster({
    radius: this.props.radius,
    maxZoom: 20,
    minZoom: 1,

    initial: () => ({ payment_count_sum: 0, all_coordinates: [] }),
    map: (props: any) => ({ payment_count_sum: props.payment_count, all_coordinates: [props.marker_coordinates] }),
    reduce: (accumulated: any, props: any) => { 
        accumulated.payment_count_sum += props.payment_count_sum;
        accumulated.all_coordinates = [...accumulated.all_coordinates, ...props.all_coordinates];
        },
});
```

now you can access all_coordinates:

```
const onClusterPress = (e: any, cluster: any) => {
    const region = regionContainingPoints(cluster.properties.all_coordinates);
    this.root.animateToRegion(region, 100);

   // TIMEOUT hack here?!
}
```

I am still having some problems clusters not completely expanding on some concrete latitudes/longitudes and sometimes animateToRegion() doesn't trigger calculateClustersForMap() correctly, I tried timeout and it makes it a bit better, but still not good enough. I will do some more investigation.

**Comment by venits** [comment]
I released new version of this library.

In new module expanding cluster is set up by default 🎉
