### ISSUE TITLE
Markers do not appears

### ISSUE THREAD

**Issue by danchokobo** [venits/react-native-map-clustering#70]
I render coordinates from API, and while loading this props, markers do not appears. Help me
Without clustering markers perfectly shown, but with clustering MapView, markers do not shown

>
 <MapView

					provider="google"
					style={styles.map}
					region={region}
					showsMyLocationButton
					showsScale
					zoomEnabled
				>
					{this.props.markers.map(item => (
						<Marker
							style={styles.markerIcon}
							title={item.crimeTitle}
							description={item.description}
							image={item.markerIcon}
							key={`foo${id++}`}
							coordinate={{
								longitude: item.coordinates.x,
								latitude: item.coordinates.y
							}}
						/>
					))}
				</MapView>

>

**Comment by Shubham-Sinha** [comment]
Same issue.

**Comment by danchokobo** [comment]
@Shubham-Sinha Hi, I have solved issue!
I have a props isLoading, if isLoading equals true i show empty mapview, when my all markers loaded i render it
