### ISSUE TITLE
Region does not resetting

### ISSUE THREAD

**Issue by danchokobo** [venits/react-native-map-clustering#72]
Hi, in my map I am using RNGooglePlaces from 'react-native-google-places',
So before using clustering, it was working perfectly. But after changing Mapview, it does not change place after searching place. it has been stayed in the same place, even the props region was changed. Usually after setState, content is re-rendering, but here is apperead something strange. Help me

`	openSearchModal = async () => {
		const place = await RNGooglePlaces.openAutocompleteModal();
		try {
			this.setState({
				region: {
					latitude: place.latitude,
					longitude: place.longitude,
					latitudeDelta: LATITUDE_DELTA,
					longitudeDelta: LONGITUDE_DELTA
				}
			});
		} catch (error) {
			throw new Error('error occured: ', error);
		}
	};`'

 `	<MapView
					provider="google"
					style={styles.map}
					initialRegion={region}
					region={region}
					showsMyLocationButton
					showsScale
					zoomEnabled
					onPress={allowTapOnMap ? this.onMapPress : null}
					clusterColor="white"
					clusterTextColor={easternBlue}
					clusterBorderColor={easternBlue}
					clusterBorderWidth={2}
				`

**Comment by danchokobo** [comment]
@venits please help

**Comment by Nitingadhiya** [comment]
@venits  I have also same issue.
