### ISSUE TITLE
onClusterPress show Callout with marker information 

### ISSUE THREAD

**Issue by impossible-creations** [venits/react-native-map-clustering#77]
Could you please give some hint, when onClusterPress  a cluster it can show a Callout with some calculated marker information? thanks

**Comment by kkusanagi** [comment]
ya, I have the same problem on this. Could you at least capture the key or id props for us? so we can determine what marker under that cluster

**Comment by venits** [comment]
Hi, @kkusanagi 

I released new version of module, please check version **3.0.1**.

What you can do it new version is:

```js
<MapView
  preserveClusterPressBehavior
  onClusterPress={(cluster, markers) => {console.warn(cluster, markers);}}
  //rest props
>
  // markers
</MapView>
```

Now in **onClusterPress()** you will get all necessary information about cluster and markers. 
Remember to add **preserveClusterPressBehavior** otherwise map will automatically scroll to cluster.

Let me know if that works for you ;)

**Comment by kkusanagi** [comment]
Thanks for quick reply. for the markers, I had tried **preserveClusterPressBehavior** with true and false.
With true: it will only return cluster info. Undefined data on markers.
with false: it will only return cluster and markers info. but the markers only give me the coordinates info. What i really need is the key or id within the marker props.

**Comment by venits** [comment]
Hmm ok I see the problem.

I will return info about markers not matter of **preserveClusterPressBehavior**.

Are you sure markers return only coordinates?

For me marker object, looks like this:
```js
{
    "geometry": Object {
      "coordinates": Array [
        17.023723920873252,
        51.92942900764412,
      ],
      "type": "Point",
    },
    "properties": Object {
      "index": 26,
      "point_count": 0,
    },
    "type": "Feature",
  }
```

**Comment by kkusanagi** [comment]
yup. only info you showed. I can't make use of this info. As some of my location is same coordinates but different floor. I need a unique ID or Key as i had set on Marker props.

```
geometry:
coordinates: (2) [100.37444550544024, 6.097052178955843]
type: "Point"
__proto__: Object
properties:
index: 1
point_count: 0
__proto__: Object
type: "Feature"
__proto__: Object
```

**Comment by venits** [comment]
Can you show me what props are you sending in <Marker/> ?

I may be able to pass all props to properties so you can use them later.

**Comment by kkusanagi** [comment]
mostly we use "id" or default props "key" in react-native. With this info, i'll be able to identify the data.

```
<Marker
            id= {shop.key}
            key = {shop.key}
            coordinate={{
              latitude: shop.coordinates.latitude,
              longitude: shop.coordinates.longitude,
            }}
            title={shop.name}
            description=''
            onPress = {(coor)=>{
              this._openDetail(shop);
              //console.log(shop.name);
            }}
          >
          <CustomMarker shopobj={shop} image_url={shop.image_url ? {uri: shop.image_url} : null} name={shop.name} ishalal={shop.ishalal} />
          </Marker>
```

**Comment by kkusanagi** [comment]
here an old thread of [react-native-component-map-clustering](https://github.com/bamlab/react-native-components-collection/tree/master/packages/react-native-component-map-clustering)

You can check their useful hints there

**Comment by venits** [comment]
Ok, now you will get all props you passed into <Marker/> in **onClusterPress()**.

I will release new version in 1-2 hours I think :) I will let you know.

**Comment by kkusanagi** [comment]
Wow, fast. Thanks.

**Comment by venits** [comment]
@kkusanagi  I released new version **"3.0.2"** 🎉 

Please let me know if that will work for you now :)

**Comment by kkusanagi** [comment]
just a notice. Did you change for **onRegionChangeComplete** too?

**Comment by venits** [comment]
Hmm I don't think so. Did it stop working?

**Comment by kkusanagi** [comment]
For previous version 3.0.1, **onRegionChangeComplete(region, markers)**  markers also return same data as **onClusterPress()**.

So i wonder will you need to change that as well.

**Comment by venits** [comment]
Hmm **onRegionChangeComplete()** returns **region** that is different that **cluster**. Second parameters is same for both of them. But it can be omitted if you don't use it.
