### ISSUE TITLE
Callout displayed under clusters and markers

### ISSUE THREAD

**Issue by vhoen** [venits/react-native-map-clustering#78]
Sometimes when tapping on a marker it display the callout under surrounding clusters and markers.
<img width="369" alt="capture d ecran 2018-05-30 a 15 03 36" src="https://user-images.githubusercontent.com/5245902/40729012-f0d1910c-641a-11e8-9669-5c3bbe467e73.png">

I tried the same code with react-native-maps only and the callout is displayed as expected.

**Comment by vhoen** [comment]
zIndex does the trick. Thanks a lot.

**Comment by vhoen** [comment]
Reopening this issue. Problem is still there on ios despite zIndex fix (cf. screenshot)
<img width="544" alt="capture d ecran 2018-06-04 a 15 31 46" src="https://user-images.githubusercontent.com/5245902/40942334-6664b504-683d-11e8-9793-92f10e23d013.png">

A sample app can be found there : https://github.com/vhoen/mapcluster, once the map is displayed, you need to zoom a bit and tap on a marker close to a cluster.

Thanks in advance for looking at this issue.

**Comment by venits** [comment]
I released new version of this library. This issue should be solved there 🎉

**Comment by netsmertia** [comment]
How to solve this, zIndex and absolute position not working for ios. I haven't tested on android.
![image](https://user-images.githubusercontent.com/4003316/147858366-73dae13c-7945-44b6-a2c5-ba4f9ab6ef11.png)
