### ISSUE TITLE
animateToRegion

### ISSUE THREAD

**Issue by msabaeian** [venits/react-native-map-clustering#79]
hi
how i can call animateToRegion in this component?
i use ref to get map and then call animateToRegion but it doesnt work and app crash

```
<MapView 
ref = {(mapView) => this._mapView = mapView}
.... />

this._mapView.animateToRegion // not working!
```

**Comment by nitinsh99** [comment]
Hi @venits great lib..thanks..can you please add support to animatToRegion? I am getting the same issue..

**Comment by hadesownage** [comment]
Try with:
`this._mapView._root.animateToRegion({ coords })`

**Comment by gokulkulkarni1987** [comment]
You can use in the following way, I have tested it works,

`this.refs._mapview.root.animateToRegion({})`

**Comment by salimakhtar92** [comment]
You cant use this its working for me
```
<MapView
            ref = {(ref) => mapView=ref}
>
```
use following for animate:
```
const region = {
      latitude: ....,
      longitude: ...,
      latitudeDelta: .....,
      longitudeDelta: ....
    }
    mapView.root.animateToRegion(region, 1000);
```

**Comment by ReinisL** [comment]
Another approach

`<ClusteredMapView  ref = {(ref) => this.mapView = ref} />`

For animation function 
`this.mapView.getMapRef().animateToRegion({ region })`

**Comment by Milbergs** [comment]
@ReinisL your are the man!!!!

**Comment by venits** [comment]
H all, I changed implementation a little bit.
Now you have to use mapRef instead of ref.

Example:

<MapView mapRef={ref => this.mapView = ref} />

In case of any problems please open issue.
