### ISSUE TITLE
How to de-cluster on single tap 

### ISSUE THREAD

**Issue by DikshaDeep** [venits/react-native-map-clustering#80]
HI

I am using this package and right now I wnat to expand cluster when i single click on cluter markers. 

Please tell me how to do this?

i'm using  ``` onClusterPress={ (coordinates) => this.animate(coordinates) }```

```
animate = (coordinates) => {
    console.log(coordinates)
  }
```
I am getting following in log::
![image](https://user-images.githubusercontent.com/32561815/42374573-24b53e28-8136-11e8-9d32-b753bfbadd2d.png)

**Comment by salimakhtar92** [comment]
@DikshaDeep use the older version ```1.2.6``` of this package

First of all uninstall the current version of this package and install  older version. For older version run the following command from terminal
``` 
npm install react-native-map-clustering@1.2.6  --save 
```
then you will get the ```lat``` and ```long```

```
onClusterPress={ (coordinates) =>  console.log(coordinates) }
```

**Comment by venits** [comment]
I released new version of this library.

Now, de-clustering is default behaviour when pressing cluster 🎉
