### ISSUE TITLE
Map with clustering not updating the user location

### ISSUE THREAD

**Issue by matan335** [venits/react-native-map-clustering#89]
the problem is that when you send a reigon props as your state and update it, 
the state of the mapWithClustering stays the same fixed on the inital reigon

The solution:

change 

```
  componentWillReceiveProps() {
    this.createMarkersOnMap();
  }
```

to 

```
  componentWillReceiveProps(newProps) {
    this.createMarkersOnMap();
    this.setState({currentRegion: newProps.region})
  }
```

in MapWithClustering.js

found at node_modules\react-native-map-clustering\MapView\MapWithClustering.js

**Comment by mahshadalishahi** [comment]
+1

**Comment by finetuning-mg** [comment]
+1 MapView doesn't update correctly without this fix

**Comment by venits** [comment]
I released new version of this library. Now user location should be handled correctly.
