### ISSUE TITLE
Turning off clustering for Marker doesn't work

### ISSUE THREAD

**Issue by Noresourses** [venits/react-native-map-clustering#90]
Using the cluster prop on a Marker does not disable clustering for that specific Marker. 
Also, the code bellow works:
<Marker coordinate={{latitude: 38.34498159999999, longitude: 21.7373716}} cluster{false}  />
But this, taken from the readme doesn't:
    <Marker coordinate={{latitude: 52, longitude: 19}} cluster={{false}} />

**Comment by TigranPetrosyan89** [comment]
Hi, 
Is there any update on this issue?
This one doesn't work for me either: <Marker coordinate={{latitude: 38.34498159999999, longitude: 21.7373716}} cluster{false} />

**Comment by venits** [comment]
Hi, I updated Readme.
It should be: (in your case)
```js
<Marker coordinate={{latitude: 38.34498159999999, longitude: 21.7373716}} cluster={false} />
```

**Comment by TigranPetrosyan89** [comment]
Thanks for response. 
I tried the way that you provided, but the " cluster={false} " pararam is ignored in my app. 
Please take a look. Could you tell me what i'm missing?

<MapView
			region={{latitude: 52.5, longitude: 19.2,
			latitudeDelta: 25, longitudeDelta: 10}}
			radius={10}
		      style={styles.map}>
  <Marker coordinate={{latitude: 38.34498159999999, longitude: 21.7373716}} />
  <Marker coordinate={{latitude: 52.4, longitude: 18.7 }} cluster={false} />
   <Marker coordinate={{latitude: 52.1, longitude: 18.4}} />
   <Marker coordinate={{latitude: 52.6, longitude: 18.3}} />
  <Marker coordinate={{latitude: 51.6, longitude: 18.0}} />
</MapView>

**Comment by venits** [comment]
Hmm your code should work. Did you imported:
```js
import MapView from 'react-native-map-clustering';
import { Marker } from 'react-native-maps';
```
in your app?

**Comment by TigranPetrosyan89** [comment]
Sure i did it.  Is there any versions that not supporting this param? my version is  1.2.2. 
Also i'm using the OpenStreet map tile.

**Comment by venits** [comment]
Try version `1.3.1` and let me know if that worked 👍

**Comment by TigranPetrosyan89** [comment]
It worked, thank you!
