### ISSUE TITLE
How does customDefinedMarker works?

### ISSUE THREAD

**Issue by AideProjet** [venits/react-native-map-clustering#94]
Hi, 

Just installed the latest release, I don't know how to use the props "CustomDefinedMarker", 

Does somebody have an example? 

Thanks, 

Théo

**Comment by Trexy94** [comment]
this props is not present in 1.3.1 version of react-native-map-clustering, i suppose @venits will release it in the next version, however you can take as example the `MapView/CustomMarker.js` file and change it according to your needs. The prop expects that you pass a react component like that. In my implementation I replaced the styles and added an image to the marker.

then you can import the custom component and pass it in that prop.

**Comment by AideProjet** [comment]
Hey, 

Ok got it, I'll do that!

Thanks, appreciate it. 

Théo
