### ISSUE TITLE
Want to zoom in to the point where the cluster will split

### ISSUE THREAD

**Issue by matan335** [venits/react-native-map-clustering#95]
It will be nice to have infomation about the markers from the onClusterPress

The thing that I really struggles with is  that I need to zoom to the level in witch the cluster will. Split abd we can see the markers that he is made out of

**Comment by matan335** [comment]
Found a solution you can close

**Comment by RohitHegde44** [comment]
What was the solution

**Comment by matan335** [comment]
I have build a recursive function that will zoom a little bit and call itself untile one of the markers will not be visable anymore and will return the zoom level

**Comment by RohitHegde44** [comment]
How did you detect whether one of those markers is visible?

**Comment by matan335** [comment]
I calculated the distance in km from where I am to each marker and also clculated a the furdest point on the map for my view and if the distance is lower than that is means the marker is visable

search js function get distance from lat long
