### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by ViktorVojtek** [venits/react-native-map-clustering#96]
Hi, I am trying to use this package, but it doesn't seems to work on iOS devices.

When I zooming out to the view of the whole globe or zooming in to the maximum possible zoom to the street nothing changes. Markers are not clustering to groups or anything.

I am using the following:
"react-native": "0.57.8",
"react-native-map-clustering": "^1.3.1",
"react-native-maps": "^0.23.0",

Thanks in advance for any help!

**Comment by ViktorVojtek** [comment]
When i log your calculateClustersForMap method.
In the if (this.props.clustering && this.superCluster) true statement the clusters array computed from this.superCluster.getClusters() method always return an empty array.

After following trails to createMarkersOnMap method I figure out that markers and otherChildren arrays are empty too. Even after the computation, when you are trying to push items to one array or another with your if else statement inside of forEach function.

The issue is located in the marker.props.cluster. which is undefined.

In you documentation there is no such mention of that I have to add "cluster={true}" prop to every single Marker component. At least it is not obvious from the point 2. of the documentation.

Where the following stands:

<MapView
    region={{latitude: 52.5, longitude: 19.2,
             latitudeDelta: 8.5, longitudeDelta: 8.5}}
    style={{width: mapWidth, height: mapHeight}}>
    <Marker coordinate={{latitude: 52.0, longitude: 18.2}} />
    <Marker coordinate={{latitude: 52.4, longitude: 18.7}} />
    <Marker coordinate={{latitude: 52.1, longitude: 18.4}} />
    <Marker coordinate={{latitude: 52.6, longitude: 18.3}} />
    <Marker coordinate={{latitude: 51.6, longitude: 18.0}} />
    <Marker coordinate={{latitude: 53.1, longitude: 18.8}} />
    <Marker coordinate={{latitude: 52.9, longitude: 19.4}} />
</MapView>

Please update this part of your your docs to the following instead:

<MapView
    region={{latitude: 52.5, longitude: 19.2,
             latitudeDelta: 8.5, longitudeDelta: 8.5}}
    style={{width: mapWidth, height: mapHeight}}>
    <Marker coordinate={{latitude: 52.0, longitude: 18.2}} cluster />
    <Marker coordinate={{latitude: 52.4, longitude: 18.7}} cluster />
    <Marker coordinate={{latitude: 52.1, longitude: 18.4}} cluster />
    <Marker coordinate={{latitude: 52.6, longitude: 18.3}} cluster />
    <Marker coordinate={{latitude: 51.6, longitude: 18.0}} cluster />
    <Marker coordinate={{latitude: 53.1, longitude: 18.8}} cluster />
    <Marker coordinate={{latitude: 52.9, longitude: 19.4}} cluster />
</MapView>

Besides this little confusion I have to thank you for this module.
It's pretty neat and saves me a lot of work and effort.
Good job!

**Comment by venits** [comment]
Ahhh snap.
Sorry my mistake.

I changed this to: 
```js
 if (marker.props.cluster === false) {
    otherChildren.push(marker);
    return;
 }
      
 if (marker.props && marker.props.coordinate) {
...
```

Now it will not cluster only if `cluster={false}`.

I updated module to versions `1.3.2`

Let me know if that will work now for you ;)

**Comment by ViktorVojtek** [comment]
Thanks Tomasz for your quick fix and response!

This little condition treatment of your forEach loop will definitely work!

I have updated your module to version 1.3.2, but somehow I still have the original source from version of 1.3.1.
But this could also be an issue with github versioning, I don't know...

Anyway, this fix works! Great job!

**Comment by venits** [comment]
Ye it is often a problem cache. 
You can try running:
`npm start -- --reset-cache`
or if you are using expo:
`exp r -c`

And restart your project ;)

**Comment by quangnguyen511** [comment]
@venits  just installed this library but it's still keeping the old code
React.Children.forEach(this.props.children, (marker) => {
      if (marker.props && marker.props.coordinate && marker.props.cluster) {
        markers.push({
          marker,
          properties: { point_count: 0 },
          geometry: {
            type: 'Point',
            coordinates: [
              marker.props.coordinate.longitude,
              marker.props.coordinate.latitude,
            ],
          },
        });
      } else {
        otherChildren.push(marker);
      }
    });
What will i change to ?
