### ISSUE TITLE
Pressing Marker and changing it making it disappear 

### ISSUE THREAD

**Issue by matan335** [venits/react-native-map-clustering#97]
When pressing on a marker I want it to show an image and as a result the marker's children change

The problem is that as soon as I'll press a marker near a cluster the markers will disappear.
after Ill zoom in and out it seems to be fine but is there a way to make It work more sufficiently?

Before pressing anything:
![img_0028](https://user-images.githubusercontent.com/40234607/52424620-0b89fe80-2b03-11e9-8da0-5d9aef7488df.jpg)

After pressing:
![img_0029](https://user-images.githubusercontent.com/40234607/52424669-1e9cce80-2b03-11e9-8905-eff79a4ccc86.jpg)

And after some zoom:
![img_0030](https://user-images.githubusercontent.com/40234607/52424699-2d838100-2b03-11e9-9457-5003d67a59b6.jpg)

Tried cluster prop on the marker I have pressed but it didn't work

Please help!!

**Comment by sarishti** [comment]
I am facing same issue

**Comment by venits** [comment]
I released new version of this library. This issue is solved in new release 🎉

**Comment by mchemweno** [comment]
I am experiencing the same issue
