### ISSUE TITLE
Why remove children data onClusterPress on versions 1.3.0 and above?

### ISSUE THREAD

**Issue by matan335** [venits/react-native-map-clustering#98]
this is such an important information for us developers

please fix that we want to get the children on the cluster 
onClusterPress(croods,children)

on versions 1.2.8 
why get all the informatin we need
but on version 1.3.0 childeren is undefined 

why is that?

**Comment by venits** [comment]
I released new version of this library. **onClusterPress()** now returns: cluster data and as second parameter all markers info 🎉
