### ISSUE TITLE
Type error: null is not a defined object(evaluating: 'marker props')

### ISSUE THREAD

**Issue by rashrao76** [venits/react-native-map-clustering#99]
I have been using MapView and Marker component of react-native-maps in my project. It works absolutely fine.
I wanted to use clusters in my map so i used this library
import Marker from 'react-native-maps';
import MapView from 'react-native-map-clustering';

getting this error
![image](https://user-images.githubusercontent.com/39483427/53477111-008b1400-3a9a-11e9-8ff6-075b2feceaab.png)

React versions used:
"react": "^16.3.2",
"react-native": "^0.55.3",
"react-native-map-clustering": "^1.3.2",
"react-native-maps": "^0.23.0",

**Comment by unnamed92** [comment]
same here

**Comment by joyridedev2019** [comment]
Same here, Please resolve

**Comment by mscmateus** [comment]
same here

**Comment by venits** [comment]
I released new version of this library. This issue is solved in new release 🎉
